### ISSUE TITLE
Deploy a database

### ISSUE THREAD

**Issue by Mobilpadde** [rancher/rio#1004]
First of, lovely project! :dancer: 

I just have one problem, as I can't figure how to deploy a database with rio? Fx, mongodb or postgres.

Hope you can point me in the right direction!

Best

**Comment by rancher-max** [comment]
I believe this was answered on our Users Slack, but in case anyone else is wondering the same thing, the answer provided was:

Rio is currently focused on stateless workloads. While we plan to add support for "Stateful sets" (and Rio has some minor support for them internally at the moment) we currently only recommend Rio for stateless applications.
Refer to Issue: https://github.com/rancher/rio/issues/381 for that enhancement.
