### ISSUE TITLE
volume not listing if created in run command

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rio#103]
Steps:
1.  rio run -v test2:/data nginx
2.  rio volume

Results:  test2 is not being listed.   Should be listed.

**Comment by vincent99** [comment]
This is currently creating an ephemeral volume, which makes sense if defined in yaml but doesn't match user expectation like in `docker run`.  So for the CLI only, `-v foo:/path` should first create a volume and then use that volume for the container to be run.  When the container is deleted, the volume stays around unless deleted manually.

**Comment by tfiduccia** [comment]
No longer an option
