### ISSUE TITLE
Feature request: deploy from local folder

### ISSUE THREAD

**Issue by gilsdav** [rancher/rio#1033]
**Feature Request**
Possibility to **deploy** from a **local folder**.
I think this is a missing feature from other PaaS tools like:

- _CloudFoundry deploy using `cf push`_
- _Direct deployment from Visual Studio to Azure Web App_

It can be interesting to do exactly the same that from github (using a dockerfile) but by uploading the folder to build (without using git).

**Current result**
> couldn't parse image reference "./node-test-rio/": invalid reference format

**Comment by StrongMonkey** [comment]
https://github.com/rancher/rio/blob/master/docs/developing-application-using-rio.md Is this you are looking? We already support building and deploying application from your local folder.

**Comment by gilsdav** [comment]
That's exactly what i thought, thank you :)
Sorry for the waste of time.
