### ISSUE TITLE
Redirect to HTTPS always

### ISSUE THREAD

**Issue by Mobilpadde** [rancher/rio#1057]
**Describe the bug**

**To Reproduce**

1. Navigate to any http domain of a deployed app on rio

**Expected behavior**

Would love if the http version redirected to https. Alas cannot find a way?

**Kubernetes version & type (GKE, on-prem)**: `kubectl version`
```
╰─⠠⠵ kubectl version                             
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"archive", BuildDate:"2020-07-01T16:28:46Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2+k3s1", GitCommit:"cdab19b09a84389ffbf57bebd33871c60b1d6b28", GitTreeState:"clean", BuildDate:"2020-01-27T18:09:26Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```
Type:
**Rio version**: `rio info`
```
╰─⠠⠵ rio info       
Rio Version: v0.7.1 (d4c5f274)
Rio CLI Version: v0.7.1 (d4c5f274)
Cluster Domain: ti3ctm.on-rio.io
Cluster Domain IPs: 62.210.116.34
System Namespace: rio-system
Wildcard certificates: ti3ctm.on-rio.io(true
```
**Additional context**
`rio system logs`
output:
```
Logs are working as supposed
```

**Comment by StrongMonkey** [comment]
https://github.com/rancher/rio/blob/master/docs/router.md#redirect Https redirect feature can added through here.

**Comment by Mobilpadde** [comment]
Hmm, I'd swear I've used that method before. Oh, well, it works now! 

Thanks, @StrongMonkey! :man_dancing:
