### ISSUE TITLE
After adding weight, endpoints changes from nip.io to lb.rancher.cloud

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rio#11]
Steps:
1.  rio run -p 80/http --name test/srvmesh ibuildthecloud/demo:v1
2. rio stage --image=ibuildthecloud/demo:v3 test/srvmesh:v3
3. rio ps (notice that extention for the endpoint is nip.io
4. rio weight test/srvmesh:v3=50%
5. rio ps

Results: The extension is now lb.rancher.cloud

**Comment by StrongMonkey** [comment]
nip domain is the fallback domain we use if we can't contact api.lb.rancher.cloud. If calls to api.lb.rancher.cloud succeed it will still use our domain service.

**Comment by tfiduccia** [comment]
No longer valid with rio rewrite.
