### ISSUE TITLE
rio kubectl get nodes - version has "+$Format:%h$" text in it

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rio#13]
Steps:
1.  rio kubectl get nodes - version

Results: v0.0.0-master+$Format:%h$

**Comment by StrongMonkey** [comment]
@ibuildthecloud will fix this in our version of kube-lite.

**Comment by StrongMonkey** [comment]
available to test on v0.0.4-rc1.

**Comment by tfiduccia** [comment]
Version - v0.0.4 rc1
Verified fixed
