### ISSUE TITLE
inspect domain doesn't work

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rio#131]
Steps:
1.  rio run -p 80/http -n tsk1/tsvr1 nginx:latest
2.  rio domain add test.foo.bar tsk1/tsvr2
3.  rio inspect test.foo.bar

Results - nothing happens.  I expect I should inspect a domain somehow but I'm not sure how I should be able to do that.

**Comment by StrongMonkey** [comment]
@tfiduccia inspecting the id should work. We have to add special logic to be able to inspect domain based on domain name. To get id run `rio domain ls --ids`.

**Comment by tfiduccia** [comment]
Version - v0.1.1-rc1
Verified fixed.
