### ISSUE TITLE
promote back to version, version to goes to 50% and gets stuck

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rio#229]
Version - v0.1.0-rc12

Steps:
1.  rio run -p 80/http --name svc --scale=3 ibuildthecloud/demo:v1
2.  rio stage --image=ibuildthecloud/demo:v3 default/svc:v3
3.  rio promote default/svc:v3
4.  rio revision default/svc, wait until v3 is equal to 100%
5.  rio promote default/svc:v1
6.  rio revision default/svc

Results:
The two version go to 50% and just get stuck there.  I realized that I what I really need to do is go back to v0, then it will resume.

**Comment by cbron** [comment]
@rancher-max can you retest this in 0.6, should be fixed

**Comment by rancher-max** [comment]
Fixed in v0.6.0-alpha.2
