### ISSUE TITLE
registry does not start due to cert-checker error

### ISSUE THREAD

**Issue by gbaeke** [rancher/rio#231]
rio install against AKS 1.13.5 

registry deployment stays at 0/2; error in the cert-checker init container is:

Can't open /etc/registry/tls.crt for reading, No such file or directory
140601283124072:error:02001002:system library:fopen:No such file or directory:crypto/bio/bss_file.c:72:fopen('/etc/registry/tls.crt','r')
140601283124072:error:2006D080:BIO routines:BIO_new_file:no such file:crypto/bio/bss_file.c:79:
unable to load certificate

**Comment by StrongMonkey** [comment]
@gbaeke  We are running some rate-limiting issues with letsencrypts and registry requires a valid cert. So in the latest rc we change to use staging certs(until Letsencrypts recognize that on-rio.io are on the publicdomain suffix) and changed how we deployed registry service. If you can download and try the latest rc.

**Comment by gbaeke** [comment]
@StrongMonkey Tnx! This worked for me! (AKS)
