### ISSUE TITLE
Erroneous claim of running on EKS or of requiring Kubernetes 1.13

### ISSUE THREAD

**Issue by bmulling** [rancher/rio#232]
The latest Kubernetes release that EKS supports is 1.12. Rio requires 1.13 but claims on run on EKS. Either Rio can run on 1.12 or it can't run on EKS ><

**Comment by tfiduccia** [comment]
@bmulling - we would prefer if it run on the current version of kubernetes.  But it will run on 1.12 for EKS.  So we are going to leave the docs as is.

**Comment by bmulling** [comment]
@tfiduccia Thanks for the explanation! I wasn't trying to be pedantic but as someone who's running Rancher on EKS I'm interested in Rio, and the docs were confusing.
