### ISSUE TITLE
Need to throw error if weight format incorrect

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rio#248]
version - v0.1.1-rc1

Steps:
1.  rio run -n test1 nginx
2.  rio weight default/test1:v0=50%
3.  rio ps

Results: Nothing happens and the weight doesn't change to 50%.  Should throw error if this is not the correct format anymore.

**Comment by izaac** [comment]
The default version is `v0` after deploying a service. That won't change the weight if that's the only revision.

We should create a new revision in order to be able to set the `v0` weight to 50%. With this command:

`rio weight default/test1:v0=50%`

Closing.
