### ISSUE TITLE
Can't set tty to false

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rio#251]
Version - v0.1.1-rc1

Steps:
1.  rio run -n ttysvc2 --tty false nginx
2.  kubectl get po -n default 
3.  kubectl get -n default -o=yaml pod/"ttysvc2 po name"

Results:  tty is set to true.  I also tried --tty=false.  Still wouldn't change.

**Comment by StrongMonkey** [comment]
Tty is a bool flag. So to set it to true you just run `rio run --tty svc`. To set it to false do not present the flag. @tfiduccia
