### ISSUE TITLE
Create namespace on run command if it doesn't exist.

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rio#253]
Version - v0.1.1-rc1

Steps:
1.  rio run -n tnp/test1 nginx

Results: namespaces “tnp” not found.  We should create the namespace if it doesn't exist.

**Comment by flostadler** [comment]
I‘d love to start contributing to Rio. Is this a good starter issue?

**Comment by StrongMonkey** [comment]
@flostadler I have already fixed this but you are welcome to contribute to other issues :)

**Comment by tfiduccia** [comment]
Version - v0.2.0-rc1
Verified fixed
