### ISSUE TITLE
Cant delete domains that are a single word

### ISSUE THREAD

**Issue by stvnksslr** [rancher/rio#254]
Version - v0.1.1-rc1

<img width="293" alt="Screen Shot 2019-05-22 at 5 43 41 PM" src="https://user-images.githubusercontent.com/9701252/58211178-361a5480-7cb9-11e9-9f1e-78cefb6de1f5.png">
<img width="412" alt="Screen Shot 2019-05-22 at 5 43 53 PM" src="https://user-images.githubusercontent.com/9701252/58211180-374b8180-7cb9-11e9-8d09-f675c977e1f9.png">

I made a domain that was not in the proper .notation by accident so for example stvnksslr is now a domain but when i try to delete it the deletion fails.

steps to replicate 

```
rio domain add cats
rio domain rm cats
```

**Comment by tfiduccia** [comment]
Version - v0.1.1-rc1
I was able to reproduce this bug.  Although the steps should be:
1.  rio domain add cats default/servicename
2.  rio domain rm cats

**Comment by stvnksslr** [comment]
Fixed in RC3
