### ISSUE TITLE
List of options missing from run

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rio#255]
Version - v0.1.1-rc1

Comments:  There are some options that are no longer supported in rio and i just want to make sure we intended to no longer support these options.

- [ ] --cap-add & --cap-drop
- [ ] --entrypoint
- [ ] --expose
- [ ] --group-add (changed to group?)
- [ ] --health-retries (changed to health-failure-threshold?)
- [ ] --init
- [ ] --ipc
- [ ] --memory-limit (changed to memory?)
- [ ] --metadata
- [ ] --network
- [ ] --pid
- [ ] --publish
- [ ] --privilege
- [ ] --ready-cmd, ready-interval, ready-retries, ready-start-period, ready-timeout, ready-url
- [ ] --restart (how do I run once?)
- [ ] --stop-timeout
- [ ] --security-opt
- [ ] --tmpfs
- [ ] --unhealthy-retries
- [ ] --unready-retries
- [ ] --update-order
- [ ] --update-strategy

**Comment by cbron** [comment]
All of these have been addressed in refactor. Looking through the new params list I don't see anything not in use.
