### ISSUE TITLE
On Docker Mac build, connection failed for service mesh

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rio#26]
Steps:
1.  rio run -p 80/http --name test/srvmesh ibuildthecloud/demo:v1
2.  rio stage --image=ibuildthecloud/demo:v3 test/srvmesh:v3
3.  rio weight test/srvmesh:v3=90%
4.  rio ps
5.  Grab endpoint
6.  In terminal : curl -v <endpoint>

Results:  Connection failed - Network is unreachable

**Comment by StrongMonkey** [comment]
@tfiduccia This should be the duplicate of https://github.com/rancher/rio/issues/47. Can you re-test?

**Comment by tfiduccia** [comment]
Version - v0.0.3
Verified fixed
