### ISSUE TITLE
run --rollout-interval --rollout-increment options are overwritten by promote/weight defaults

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rio#268]
Version - 0.1.1-rc2

Steps:
1.  rio run -p 80/http --name svc --scale=3 --rollout-increment 10 --rollout-interval 20 ibuildthecloud/demo:v1
2.  rio stage --image=ibuildthecloud/demo:v3 default/svc:v3
3.  rio promote default/svc:v3
4.  rio revision default/svc

Results:  svc is still being promoted at 5% every 5 seconds.  Should be 10 every 20 seconds.

**Comment by davidnuzik** [comment]
To re-test v0.6.x (post Kubecon)

**Comment by cbron** [comment]
Due to switch away from increment/interval towards duration, this is no longer possible. There is also a default on duration so a user should expect that default would override any previous settings.
