### ISSUE TITLE
On very first start-up, there are no ports so build fails

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rio#27]
Version - v0.0.3-rc1
Steps:
1.  Build rio on a fresh machine with no previous rio installed

Results:  Build fails cause there are no ports and lb doesn't allow for that.
ERRO[2896] StackController /default-265db573 [stack-deploy-controller] failed with : waiting for cluster domain 
ERRO[3016] VirtualServiceController _all_ [gateway-controller] failed with : Service "rio-lb" is invalid: spec.ports: Required value

**Comment by SvenDowideit** [comment]
same on `v0.0.3-rc6`

**Comment by tfiduccia** [comment]
No longer valide
