### ISSUE TITLE
registry-proxy fails to start on rancherOS

### ISSUE THREAD

**Issue by bhale** [rancher/rio#273]
I deployed RancherOS-based cluster on VMware using Rancher UI,  then ran `rio install`.

All of the components in the rio-system namespace start successfully with the exception of registry-proxy. It appears it could be looking for ip4_forward to be set. 

The logs from each pod: 
```
+ trap exit TERM INT
+ cat /proc/sys/net/ipv4/ip_forward
+ '[' 0 '!=' 1 ]
+ exit 1
```

**Comment by resolute21** [comment]
Solved on latest version, just download rc2.

**Comment by bhale** [comment]
rc3 works great. Thank you!
