### ISSUE TITLE
Rio doesn't support clusters with `oidc` authentication

### ISSUE THREAD

**Issue by jpapejr** [rancher/rio#282]
After running `rio install` several times and just getting a simple - `FATA[0000] can't contact Kubernetes cluster. Please make sure your cluster is accessable `, I started running other commands like `rio console` and saw this: `No Auth Provider found for name "oidc"`. 

So two things: 

1. The error coming off the `rio install` command could do a better job of telling me why it didn't work (`--debug` didn't help produce any more hints what was wrong either)

2. The real problem: no support for OIDC auth.. 😢

**Comment by StrongMonkey** [comment]
@jpapejr yes, we already had a pr for this issue https://github.com/rancher/rio/pull/264...

**Comment by StrongMonkey** [comment]
This should be fixed by the PR mentioned in previous comment. @jpapejr
