### ISSUE TITLE
Migrate to Tekton TaskRuns

### ISSUE THREAD

**Issue by ImJasonH** [rancher/rio#283]
Hi, I'm Jason 👋, I chatted about this a bit with @ibuildthecloud at KubeCon in Barcelona last week. I'm the WG lead for Knative Build and a core contributor to the Tekton Pipelines project.

----- 

Rio currently uses [knative/build](https://github.com/knative/build) to perform pre-deployment builds from source. This seems to work just fine for now, and if it's working for you there's no urgent need to move off of it, but it might be worth migrating to [Tekton](https://tekton.dev), specifically, Tekton's analogue of `Build`, which is the `TaskRun` type.

This type is heavily based on `Build` -- having been largely built by the same group of people -- with more active development and some useful features, like the ability to report built image(s) by digest, and significant logging improvements enabled by not using k8s init containers. Tekton also sees significantly more active development than Knative Build, so you should expect new features and bug fixes to land in Tekton, if they're ever backported to Build at all.

Tekton includes more features that might not be useful to Rio, such as Pipelines, Resources, etc., but those types are entirely optional, and shouldn't have any significant performance or resource requirements overhead. It's a perfectly well-supported and expected use case to only use `TaskRun`s, like Rio would.

-----

I took a look through the codebase to see where changes might need to be made in order to migrate to Tekton:

1. Generate client libraries and fakes in the [rancher/wrangler-api](https://github.com/rancher/wrangler-api) repo ([here](  https://github.com/rancher/wrangler-api/blob/master/pkg/codegen/main.go#L85)) -- I attempted to do this [in my fork](https://github.com/rancher/wrangler-api/compare/master...ImJasonH:master), but `go generate` seemed to pull in unnecessary directories and generally just messed everything up. 🤷‍♂  -- let me know if there's something I'm obviously doing wrong and I can submit a more formal PR if I get it all working. If I can get past this step I'm happy to continue to the next and so on with some guidance.

1. [Install Tekton components](https://github.com/tektoncd/pipeline/blob/master/docs/install.md) instead of (or alongside) Knative Build components. These components shouldn't require any more/less resources than the existing Build components, since they largely do the same thing: watch for resource creations, start Pods, watch Pods, and update resource statuses -- none of which requires much by way of processing in the controller components themselves.

1. Update [the `build` `service` module](https://github.com/rancher/rio/blob/2771703b180bfe316567d6bc7242cf5490c8358f/modules/build/controllers/service/controller.go#L122) to create `TaskRun`s instead of `Build`s. This should be a largely mechanical change, since the types are so similar. I have a WIP guide describing the differences [in a gist](https://gist.github.com/ImJasonH/2d183e5f474bc31669c7461a26f460ec), which I expect to promote to more "official" documentation soon.

1. Update [the `build` module](https://github.com/rancher/rio/blob/2771703b180bfe316567d6bc7242cf5490c8358f/modules/build/controllers/build/controller.go#L24) to speak in terms of `TaskRun`s instead. As with `Build`s, watch a created `TaskRun` to see if it contains a `Condition` indicating that it completed (un)successfully and update the `Service` accordingly.

1. Update [the `buildkit` `ClusterBuildTemplate`](https://github.com/rancher/rio/blob/2771703b180bfe316567d6bc7242cf5490c8358f/stacks/build-stack.yaml#L174) to use [the `buildkit` `ClusterTask`](https://github.com/tektoncd/catalog/tree/master/buildkit) instead.

1. Update [`tables` package](https://github.com/rancher/rio/blob/2771703b180bfe316567d6bc7242cf5490c8358f/cli/pkg/tables/builds.go) to speak in terms of `TaskRun`s.

... and probably some other stuff I'm overlooking, which we'll find out along the way.

-----

I'm more than happy to help with or drive this migration, if there's interest in doing it.

On the one hand, existing releases of Build aren't going anywhere, and seem to work just fine for you. On the other, new features and improvements are likely going to happen in Tekton going forward, so boarding that train should be worthwhile.

**Comment by StrongMonkey** [comment]
@ImJasonH Hi Jason, Thank you for putting effort into it! I've already talked with @ibuildthecloud and yes we are planning to migrate Rio build component from knative build to Tekton in the next milestone. I've already started looking at the api types of Tekton and probably going to start the work in next week.

**Comment by ImJasonH** [comment]
Fantastic! Please let me know if you have any questions/problems/etc that I can help you with. 👍

**Comment by StrongMonkey** [comment]
Tekton build is already added by this pr(https://github.com/rancher/rio/pull/318).
