### ISSUE TITLE
rio install - fails to install on DigitalOcean Kubernetes 1.14

### ISSUE THREAD

**Issue by alexellis** [rancher/rio#302]
I had an issue running `rio install` on DigitalOcean Kubernetes with 1.14

```
$ curl -sfL https://get.rio.io | sh -

$ rio install
FATA[0000] nodes is forbidden: User "system:anonymous" cannot list resource "nodes" in API group "" at the cluster scope 
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by alexellis** [comment]
@ibuildthecloud any thoughts?

**Comment by StrongMonkey** [comment]
I don't have any issue installing rio in DigitalOcean Kubernetes. By any chance do you have auth provider in your kubeconfig?

**Comment by alexellis** [comment]
How are you accessing the KUBECONFIG file? Are you downloading or pulling it in via doctl kubeconfig save?

Both act differently.

**Comment by alexellis** [comment]
IMHO both methods need to work to be useful. I can try again next week.

**Comment by alexellis** [comment]
Since the issue was opened in early June this issue appears to have gone away (at least from a Linux client, I was using MacOS before)

There are some odd issues with SealedSecrets when using the DO kubeconfig from `doctl k8s cluster save` vs the downloaded config file from the UI.

**Comment by alexellis** [comment]
For more info on "funky things" with DO's auth mechanism and config files, see a similar issue here: https://github.com/bitnami-labs/sealed-secrets/issues/183

**Comment by daxmc99** [comment]
@alexellis  I was able to install on DO manged k8's `1.15.3-do.2` (downloading the config file manually).
