### ISSUE TITLE
0% weighted deployments does not show up on `rio ps`

### ISSUE THREAD

**Issue by nfons** [rancher/rio#309]
To reproduce:

run a service with 2 revisions:

`rio run -p 80/http --name svc --scale=3 ibuildthecloud/demo:v1`

 note the app running via:

`rio ps`

stage a new version:

`rio stage --image=ibuildthecloud/demo:v3 default/svc:v3`

According to the README / guide running `rio revision` should return:

`default/svc   25 minutes ago   https://svc-default.0q0608.on-rio.io:9443   v0, v3          3         100%    `  

HOWEVER:

it will only output:

`default/svc   25 minutes ago   https://svc-default.0q0608.on-rio.io:9443   v0          3         100%   `   

Set the weights manually for the revisions:

`rio weight default/svc:v0=5% default/svc:v3=95%`

now you will see correct output when doing `rio ps`

Is this correct functionality? its incorrect from README, and I think would be beneficial to show 0% weighted items

**Comment by tfiduccia** [comment]
Version - 0.2.0-rc1
This is indeed an issue and we don't show both versions when 1 of them is 0% like the docs say.

**Comment by StrongMonkey** [comment]
We made the change at the some point that zero-weight service are not showed in `rio ps` by default. The docs should already be accommodated to reflect the change. But this might need to rethink or redesigned to see if that is a better way to show this info.
