### ISSUE TITLE
build Back-off pulling

### ISSUE THREAD

**Issue by WJXZ** [rancher/rio#329]
Back-off pulling gcr.io/knative-releases/github.com/knative/build/cmd/controller@sha256:77b883fec7820bd3219c011796f552f15572a037895fbe7a7c78c7328fd96187

**Comment by StrongMonkey** [comment]
There is an issue where certain images will not be pulled if gcr.io registry is blocked. We are going to mirror those images under rancher repo.

**Comment by StrongMonkey** [comment]
This is fixed in v0.4.0-rc2. All images are mirrored on dockerhub.
