### ISSUE TITLE
How to Connect to a External DB Service with Port running outside K8S Cluster

### ISSUE THREAD

**Issue by mkharibalaji** [rancher/rio#334]
Hi Guys,
        First of all a wonderful work around istio and knative.I am just loving Rio.I need to connect to a mongoDB service running with TLS with a particular ip and port outside the K8S Cluster.In Istio we create using ServiceEntry but in Rio when trying to use External Service I was not able to add port no.

Any help would be great.

Thanks,
Hari

**Comment by StrongMonkey** [comment]
are you looking for https://github.com/rancher/rio/blob/master/docs/README.md#adding-external-services?

**Comment by StrongMonkey** [comment]
You can try `rio externalservice add $name IP:PORT`.

**Comment by pilayar76** [comment]
Hi Guys,

It's working with external in version 0.2.0. Also, do we have a provision to send the run time variables to the container image from Rio CLI?

**Comment by mkharibalaji** [comment]
Hi @pilayar76 ,
        Thanks a lot.Yes it works and the name should be in lowercase.

@StrongMonkey - Is it intended way that the name should be in lowercase ?

**Comment by StrongMonkey** [comment]
The name should follow the standard DNS name that k8s requires.

**Comment by StrongMonkey** [comment]
@mkharibalaji The syntax should be `rio external create protocl://host:port`.

**Comment by mkharibalaji** [comment]
Thanks a lot @StrongMonkey
