### ISSUE TITLE
How to send values using environment variables from Rio which is declared inside a container?

### ISSUE THREAD

**Issue by pilayar76** [rancher/rio#337]
Hi Guys,

I have a docker image which prints "Hello World" from a document inside MongoDB. In that, I am trying to send connection string of mongo db in runtime like below using kubectl.

kubectl apply -f helloworld.yaml
 -env:
    name: MONGODB_URI
    value: mongodb://localhost/test

Can you please help me to understand how to dynamically pass the values to the variables declared inside the container?

Thanks,
Raja

**Comment by StrongMonkey** [comment]
are you looking for `rio run --env`? you can add any environment variable by passing options `--env` and `--env-file`. For more references `rio run -h`.

**Comment by davidnuzik** [comment]
An answer was provided; please let us know if you need anything else. We can re-open the issue if necessary.
