### ISSUE TITLE
Redirect Logging to ELK or FileSystem etc.,

### ISSUE THREAD

**Issue by mkharibalaji** [rancher/rio#338]
Hi @StrongMonkey,
            How to redirect the logs of the application to ElasticSearch/Filesystem or any other option that fluentd supports.How to customize it ?

Thanks & regards,
Hari

**Comment by StrongMonkey** [comment]
@mkharibalaji At this point Rio doesn't really manage logging for you. So you might have to look at documentation on how to setup ElasticSearch/Fluentd in Kubernetes.

**Comment by mkharibalaji** [comment]
Thanks a lot @StrongMonkey
