### ISSUE TITLE
rio doesn't support hostNetwork

### ISSUE THREAD

**Issue by harutyundermenjyan** [rancher/rio#343]
Hello,
The use case of the hostNetwork is because the network of our servers configured with bonding, so where the bonding effect is needed I forcedly using the hostNetwork even though it's not good for containerized environments. Also, I don't want to use flannel host-gw option which will limit us in layer2 level and not allow to scale cluster out of layer2 switch. If the rke(or k8s can't be sure here) will support flannel DirectRouting option all problems will be solved and will no any need to use hostNetwork as well.
I'll be happy if there will be another choice instead of host Network to solve this problem, but as there is not it will be good if you add the host Network support as well.

**Comment by StrongMonkey** [comment]
This will be implemented along with RBAC work(https://github.com/rancher/rio/issues/298). We need to implement a new RBAC rule that allows user to create services with HostNetworking. And it will be turn off by default unless user specifically turn it on.

**Comment by StrongMonkey** [comment]
To test this feature:
To enable hostNetworking in cli: `rio run --net=host image`.
To enable hostNetworking in cli: 
```yaml
services:
  foo:
    image: ${image}
    net: host
```

**Comment by tfiduccia** [comment]
Version - 0.4.0-rc1
hostNetwork sets to true in rio & in kubectl deployment
