### ISSUE TITLE
More enhancement for Riofile

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rio#355]
* Add `rio stack` in CLI. Stack will be the API backend support what Riofile defines. Should be able to do edit, inspect and rm on stacks.
* `rio edit` should support Riofile format.
* `rio export` should support Riofile format.

**Comment by StrongMonkey** [comment]
Available to test in v0.4.0-rc1:
Introducing `Stack` concept: Stack represents one Riofile. 
To create a stack, run `rio up`.(currently Directory should have Riofile)
To create a stack based on a specific file, run `rio up -f $file`
To create a stack based on a remote file, run `rio up -f http:/file`
To create a stack to watch a git repo, run `rio up http://git-repo.git`. (Push any changes to this repo, it should automatically watch and refresh)

`rio edit` will have the pretty edit format by default.
`rio export` will have both pretty and raw k8s format. Use `--stack` to switch.

**Comment by tfiduccia** [comment]
Version - v0.4.0-rc2
Verified all three formats for up.
