### ISSUE TITLE
rio ps and rio revision shows different scale numbers

### ISSUE THREAD

**Issue by harutyundermenjyan** [rancher/rio#364]
rio version v0.3.1 (e4253f2e)
steps to reproduce:
1. `rio run -p 8080/http --name demo monachus/rancher-demo:yellow`
2. `siege -b -c200 https://demo-default.$DOMAIN.on-rio.io:9443/load`

**Comment by StrongMonkey** [comment]
@harutyundermenjyan Can you test with latest rc v0.4.0-rc3? I don't see the problem right now.

**Comment by harutyundermenjyan** [comment]
Yes, it behaves correctly now.
Thank you for fix and contacting me by considering my opinion before closing it.
