### ISSUE TITLE
[EPIC] - RBAC/Security

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rio#378]
This issue is for tracking efforts around RBAC and security with relation to permissions model, etc.

https://github.com/rancher/rio/issues/298

**Comment by davidnuzik** [comment]
Sync with Daishan for help validating this.

**Comment by davidnuzik** [comment]
@davidnuzik has documentation requirements; needs docs issue.

**Comment by rancher-max** [comment]
Issue 618 mentioned above is related to Rancher, so this is working as expected for Rio in v0.6.0-alpha.2 as 630 has been resolved.
