### ISSUE TITLE
Expand service to run StatefulSets

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rio#381]
This issue is for tracking effort for expanding the service to run StatefulSets
We also discussed the possibility of Advanced StatefulSets

**Comment by izaac** [comment]
We need to get a sample `Riofile` to start testing the scenarios Persistent, Not-Persistent, Ephemeral.

 I tried today with 
- a Riofile with kubernetes objects.
- An edited Riofile with only Rio definitions.

Still not getting sts (statefulset) deployed. @StrongMonkey mentioned he would go through the configuration and provide a working sample for deploying these with Rio.

**Comment by davidnuzik** [comment]
To be experimental in v0.6.0

**Comment by davidnuzik** [comment]
Closing out in favor of DeploymentWrangler effort (https://github.com/rancher/rio/issues/991) which will support StatefulSets.
