### ISSUE TITLE
Update Kiali

### ISSUE THREAD

**Issue by ticruz38** [rancher/rio#383]
Kiali currently run with version 0.14 which is 6 months old, which apparently lack Jaeger opentracing.
Any plan to update Kiali version?

**Comment by StrongMonkey** [comment]
Thanks, before we were running into a problem upgrading kiali versio. Will look into it.

**Comment by StrongMonkey** [comment]
Use this issue to track the work to update all system components to latest version in rio.

**Comment by StrongMonkey** [comment]
v0.5.0 has been shipped with latest kiali corresponding to 1.2.5 istio release.
