### ISSUE TITLE
After rio edit $NAMESPACE/$SERVICE and leaving error there rio cli doesn't work properly anymore

### ISSUE THREAD

**Issue by harutyundermenjyan** [rancher/rio#394]
rio version v0.4.0-rc1 (a9d91b75)
Steps to reproduce:
1. `rio run -p 8080/http --name demo monachus/rancher-demo:yellow`
2. `rio edit default/demo`
3. edited and added `hostNetwork: "true"` (save and exit from edit mode)
4. `rio ps` or other rio command even `rio uninstall` doesn't work.
`rio ps`
```
FATA[0002] v1.ServiceList.Items: []v1.Service: v1.Service.Spec: v1.ServiceSpec.PodConfig: HostNetwork: ReadBool: expect t or f, but found ", error found in #10 byte of ...|Network":"true","ima|..., bigger context ...|6a7b273"},"spec":{"concurrency":10,"hostNetwork":"true","image":"monachus/rancher-demo:yellow","imag|... 
```
I see that it doesn't like dubble quotes at the line `hostNetwork: "true"` but can't edit and change it anymore, it returns the error printed above.
Also tried to delete all pods in NS rio-system but didn't helped.

**Comment by StrongMonkey** [comment]
@harutyundermenjyan Hi, for host-network, if you tried to edit the service, you can put `net: host` to enable host-networking. Also for CLI `rio run --net host`. To fix your errror, `kubectl get services.rio.cattl.io` and edit your service by doing `kubectl edit` should revert it back.

**Comment by harutyundermenjyan** [comment]
Hello,
I noticed another interesting thing within this problem:
I've downloaded and replaced the binary of rio version v0.4.0-rc1 with v0.4.0-rc2 and tried to install it again.
rio version shows correct `v0.4.0-rc2` but in the error it shows the old one that is `v0.4.0-rc1`
Please see below:
Harutyuns-MacBook-Pro:bin harutyun.dermenjyan$ `rio --version`
rio version v0.4.0-rc2 (e827c06e)
Harutyuns-MacBook-Pro:bin harutyun.dermenjyan$ `rio install --mode hostport`
Defaulting cluster CIDR to 10.43.0.1/16
Deploying Rio control plane....
rio controller version v0.4.0-rc1 (a9d91b75) installed into namespace rio-system
Detecting if clusterDomain is accessible...
FATA[0006] clusterdomains.admin.rio.cattle.io "cluster-domain" not found 

I test it in the cluster deployed with rke:
```Harutyuns-MacBook-Pro:~ harutyun.dermenjyan$ kdev get no
NAME                                        STATUS   ROLES          AGE   VERSION
slc-esx12-etcd1-dev                         Ready    etcd           51d   v1.14.5
slc-esx12-master1-dev.test2.picsart.tools   Ready    worker         24d   v1.14.5
slc-esx12-node1-dev                         Ready    worker         51d   v1.14.5
slc-esx12-node2-dev                         Ready    worker         51d   v1.14.5
slc-esx13-etcd2-dev                         Ready    etcd           51d   v1.14.5
slc-esx13-node3-dev                         Ready    worker         15d   v1.14.5
slc-esx13-node4-dev                         Ready    worker         51d   v1.14.5
slc-esx14-etcd3-dev                         Ready    etcd           51d   v1.14.5
slc-esx14-node5-dev                         Ready    worker         51d   v1.14.5
slc-esx14-node6-dev                         Ready    worker         51d   v1.14.5
slc-esx15-node7-dev                         Ready    worker         51d   v1.14.5
slc-esx15-node8-dev                         Ready    worker         51d   v1.14.5
slc-esx15-orch1-dev                         Ready    controlplane   51d   v1.14.5
slc-esx16-node10-dev                        Ready    worker         51d   v1.14.5
slc-esx16-node9-dev                         Ready    worker         51d   v1.14.5
slc-esx16-orch2-dev                         Ready    controlplane   51d   v1.14.5
```

**Comment by StrongMonkey** [comment]
per discussion in https://github.com/rancher/rio/issues/395, close this issue.

**Comment by harutyundermenjyan** [comment]
Actually, this issue created because it is not possible to edit, ps, export or do anything with rio command in order to fix the error with rio but not with kubectl, after leaving an error in a service manifest file the rio command always returns an error by not allowing to edit and fix it. In https://github.com/rancher/rio/issues/395 we understood that it can solved by editing the relevant service with kubectl e.g kubectl edit services.rio.cattle.io ${name} but not with rio.
