### ISSUE TITLE
Error while rio install regardless of install mode

### ISSUE THREAD

**Issue by harutyundermenjyan** [rancher/rio#395]
rio install --mode hostport
Defaulting cluster CIDR to 10.43.0.1/16
Deploying Rio control plane....
rio controller version v0.4.0-rc1 (a9d91b75) installed into namespace rio-system
Detecting if clusterDomain is accessible...
FATA[0005] clusterdomains.admin.rio.cattle.io "cluster-domain" not found

**Comment by StrongMonkey** [comment]
Thanks for reporting, I will try to reproduce this.

**Comment by StrongMonkey** [comment]
Doesn't reproduce this in v0.4.0-rc2. Can you share more information about the environment your are using?(cluster type)

**Comment by harutyundermenjyan** [comment]
I noticed another interesting thing within this problem:
I've downloaded and replaced the binary of rio version `v0.4.0-rc1` with `v0.4.0-rc2` and tried to install it again.
rio version shows correct `v0.4.0-rc2` but in the error it shows the old one that is `v0.4.0-rc1`
Please see below:
Harutyuns-MacBook-Pro:bin harutyun.dermenjyan$ `rio --version`
rio version v0.4.0-rc2 (e827c06)
Harutyuns-MacBook-Pro:bin harutyun.dermenjyan$ `rio install --mode hostport`
Defaulting cluster CIDR to 10.43.0.1/16
Deploying Rio control plane....
rio controller version v0.4.0-rc1 (a9d91b7) installed into namespace rio-system
Detecting if clusterDomain is accessible...
FATA[0006] clusterdomains.admin.rio.cattle.io "cluster-domain" not found

I test it in the cluster deployed with rke:
```
NAME                                        STATUS   ROLES          AGE   VERSION
slc-esx12-etcd1-dev                         Ready    etcd           51d   v1.14.5
slc-esx12-master1-dev.test2.picsart.tools   Ready    worker         24d   v1.14.5
slc-esx12-node1-dev                         Ready    worker         51d   v1.14.5
slc-esx12-node2-dev                         Ready    worker         51d   v1.14.5
slc-esx13-etcd2-dev                         Ready    etcd           51d   v1.14.5
slc-esx13-node3-dev                         Ready    worker         15d   v1.14.5
slc-esx13-node4-dev                         Ready    worker         51d   v1.14.5
slc-esx14-etcd3-dev                         Ready    etcd           51d   v1.14.5
slc-esx14-node5-dev                         Ready    worker         51d   v1.14.5
slc-esx14-node6-dev                         Ready    worker         51d   v1.14.5
slc-esx15-node7-dev                         Ready    worker         51d   v1.14.5
slc-esx15-node8-dev                         Ready    worker         51d   v1.14.5
slc-esx15-orch1-dev                         Ready    controlplane   51d   v1.14.5
slc-esx16-node10-dev                        Ready    worker         51d   v1.14.5
slc-esx16-node9-dev                         Ready    worker         51d   v1.14.5
slc-esx16-orch2-dev                         Ready    controlplane   51d   v1.14.5
```

**Comment by StrongMonkey** [comment]
@harutyundermenjyan Thanks for catching this. It is a CLI bug that shows up in console. The system should already be updated. You can verify that by doing `kubectl get deploy rio-controller -n rio-system -o yaml` and verify the image has been upgraded to rc2. I will put a PR to fix this. Can you also post your systemlogs in here? `rio systemslog`. I am interested in see why cluster domain is not created.

**Comment by harutyundermenjyan** [comment]
The issue started after the problem described in this issue --> (https://github.com/rancher/rio/issues/394). When rio uninstall didn't worked due tue https://github.com/rancher/rio/issues/394 I decided to telete it with kubectl and did `kubectl delete ns rio-system` after that I can't install it again for the aforementioned problem.

**Comment by StrongMonkey** [comment]
@harutyundermenjyan Can you follow my step in that issue to manually delete that invalid field by doing kubectl edit? After that, try `rio uninstall` to see if rio-system was completed deleted.

**Comment by StrongMonkey** [comment]
If you just delete rio-system, all the resources will get stuck at terminating due to the kubernete finalizer.

**Comment by harutyundermenjyan** [comment]
I specifically checked and ensured that the ns rio-system not in terminating state before re-installing it.
I've deleted it successfully before re-installing the rio by removing the `finalize` from the NS manifest.

Here the output for the steps mentioned in https://github.com/rancher/rio/issues/394 :
Harutyuns-MacBook-Pro:bin harutyun.dermenjyan$ `kubectl get services.rio.cattl.io`
*error: the server doesn't have a resource type "services"*
Harutyuns-MacBook-Pro:bin harutyun.dermenjyan$ `rio uninstall`
Deleting Rio management controller...
Waiting for Rio controller pod to be deleted...
Deleting system component services
Cleaning up finalizers for resource Feature, group admin.rio.cattle.io...
Cleaning up finalizers for resource PublicDomain, group admin.rio.cattle.io...
Cleaning up finalizers for resource App, group rio.cattle.io...
Cleaning up finalizers for resource Service, group rio.cattle.io...
```FATA[0011] v1.ServiceList.Items: []v1.Service: v1.Service.Spec: v1.ServiceSpec.PodConfig: HostNetwork: ReadBool: expect t or f, but found ", error found in #10 byte of ...|Network":"true","ima|..., bigger context ...|6a7b273"},"spec":{"concurrency":10,"hostNetwork":"true","image":"monachus/rancher-demo:yellow","imag|... ```
Harutyuns-MacBook-Pro:bin harutyun.dermenjyan$

**Comment by StrongMonkey** [comment]
Whoops, the commands should be `kubectl get services.rio.cattle.io`. Find your service and edit
kubectl edit services.rio.cattle.io ${name}

**Comment by harutyundermenjyan** [comment]
after following the steps you've mentioned above it installed successfully.
Thank you.
