### ISSUE TITLE
DNS rebind protection breaks resolving on-rio.io

### ISSUE THREAD

**Issue by deas** [rancher/rio#396]
DHCP provides me with DNS directed to a router (FRITZ!Box 7490) which offers protection against DNS rebinding attacks. I end up with `on-rio.io` not resolving. 

I can explicitly whitelist domain names on my router. The documentation of the router asks for fqn entries, but just using the tld `on-rio.io` appears to be doing the trick.

However, I assume other people will face similar issues with DNS rebinding protection so it may be worth mentioning it in the docs.

**Comment by StrongMonkey** [comment]
Feel free to contribute to our docs!
