### ISSUE TITLE
Convert running app to Riofile

### ISSUE THREAD

**Issue by chonthu** [rancher/rio#410]
Would be nice if an application built with `run` or `build` could then be exported to Riofile

**Comment by StrongMonkey** [comment]
App is the aggregation of service revisions, which is auto-generated by management control plane. For example, if you have two services revision

```
app: "my-app"
version: v0
weight: 50%
```

```
app: "my-app"
version: v1
weight: 50%
```
Then Rio will generate an App called `my-app` which manages all the revisions, and it is up to admin to allocate weight for each revision. So essentially If you want to export an Application, export all the revisions should be enough and if you have all the revisions, `App` will always generated to reflect your current revision and weight you allocated

**Comment by chonthu** [comment]
@StrongMonkey so after digging in and getting my way around the project. I've discovered you already have this:

running: `rio export --stack=1 default`
displays:
```
services:
  demo:
    image: chonthu/demo:v1
    ports:
    - "8080"
```

I'm assuming based on your comment above, you want all revisions to also be part of this export. with weights? Does the riofile have a spec I could follow for this addition or is that part of the task at hand.

**Comment by StrongMonkey** [comment]
@chonthu Check out this https://github.com/rancher/rio/blob/master/docs/README.md#riofile-reference. In riofile you can specify app, revision, weight to each service.

**Comment by davidnuzik** [comment]
Daishan provided some information. Please do re-open the issue if there are any remaining questions. I will close this issue for now.
