### ISSUE TITLE
rio revision -q flag returning error

### ISSUE THREAD

**Issue by daniel-sullivan** [rancher/rio#413]
Attempting to get a quiet revisions list like you would with rio ps -q results in an error:
```
rio revision -q
FATA[0000] template: :1:2: executing "" at <.Name>: can't evaluate field Name in type revision.ServiceData
```

Regular command works fine:
```
rio revision
NAME                                                      IMAGE                                                          CREATED          SCALE     ENDPOINT                                                                             WEIGHT    DETAIL
******-staging/frontend:389cdb09                   registry.dev.*****.internal/*****/*****:389cdb09       21 minutes ago   1         https://frontend-389cdb09-*****-staging.dev.*****.internal                   100
*snip*
```

Manually applying the formatting works as expected:
```
rio revision --format {{.Service.Name}}
frontend-389cdb09
frontend-b50de899
backend-dd5cc2af
admin-ef01962e
*snip*
```

Will have a look into what might be causing this and if simple will fix and make a pull request, if not I'll come back and complain :)

**Comment by StrongMonkey** [comment]
:+1: will fix that. It is related to `Name` field missing in this struct https://github.com/rancher/rio/blob/5b2d711128122758a1fd5537c37f5bfd5d282f4d/cli/cmd/revision/revision.go#L35.

**Comment by daniel-sullivan** [comment]
Thank you thank you! Found the issue but unfortunately Docker for Window's Kubernetes instance decided it hates me and I needed to reinstall - and then it was the end of my employer sponsored work day :) The good news is I now have a fancy WSL2 and K3S setup so hopefully can help out with anything else that I find
