### ISSUE TITLE
No cluster domain assigned

### ISSUE THREAD

**Issue by j-rewerts** [rancher/rio#428]
I seem to be having some issues getting a cluster domain. When I run `rio install`, I get:
```
Detecting that your ingress for service mesh gateway is still pending. Do you want to:
[1]: Use Service Loadbalancer
[2]: Use HostPorts (Please make sure port 80 and 443 are open for your nodes)
[3]: Wait for ingress
Select Number [] 3
rio controller version v0.4.0 (a8d35ef9) installed into namespace rio-system
Detecting if clusterDomain is accessible...
Warning: Detected that Rio cluster domain is not generated for this cluster right now
Controller logs are available from `rio systemlogs`

Welcome to Rio!

Run `rio run https://github.com/rancher/rio-demo` as an example
```

After some time, running `rio info`:
```
Rio Version: v0.4.0 (a8d35ef9)
Rio CLI Version: v0.4.0 (a8d35ef9)
Cluster Domain: 
Cluster Domain IPs: 
System Namespace: rio-system

System Components:
Autoscaler status: running
BuildController status: running
CertManager status: running
Grafana status: running
IstioCitadel status: running
IstioPilot status: running
IstioTelemetry status: running
Kiali status: running
Prometheus status: running
Registry status: running
Webhook status: running
```

So it looks like some issue with Ingress is causing me to get no cluster domain.

Rio 0.4.0. 
Kubernetes 1.14.3-gke.11.

**Comment by j-rewerts** [comment]
Is there any plans to support GKE with Ingress out of the box?

**Comment by StrongMonkey** [comment]
@j-rewerts The ingress should be supported. Can you post `kubectl get ingress cluster-ingress -n rio-system` and check if ip address is assigned to that ingress? Or feel free to join rancher-users.slack.com #rio channel to post your result. I will be there to help you troubleshoot.

**Comment by davidnuzik** [comment]
@j-rewerts still observing the issue? Could you try what Daishan suggested or close the issue if this is no longer a problem?

**Comment by j-rewerts** [comment]
Yeah I'll close until I've got some time to check out Rio more.
