### ISSUE TITLE
CLI Review

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rio#429]
Rio CLI needs review.
- Ensure UX makes sense
- Ensure all arguments make sense
- Compare to UI - make sure CLI versus UI makes sense.

**Comment by davidnuzik** [comment]
@StrongMonkey to transfer comment from internal Slack and QA to ensure that the CLI matches the specifications and execute regression tests.

**Comment by StrongMonkey** [comment]
```
rio -s => alias for "rio -n rio-system"
rio (--all-namespace/-A) ps should in system
rio default to single namespace ClientConfig might have default namespace


NAEMSPACE   NAME                   APP  VERSION
namespace   type/namespace/name    app  version

NAME
type/name

type is optional if service.

types
=====
service => rio service
secret
configmap
domain
stack
router

ps
    endpoint -> version specific
    image
    weight
    app
    version
    scale = (scale-unavailable)/scale
    detail?

    drop -c no containers

    rio ps foo is not support
    rio ps -a drop header

edit
    drop --raw

export
    drop --type
    drop --raw
    default to k8s
    --riofile

logs => use stern from linkerd

drop revision

drop console

systemlogs include more pods with --all/-a

rio build to be rio up minus deploying

rio feature drop

rio route pretty in riofile
```

**Comment by izaac** [comment]
opened https://github.com/rancher/rio/issues/616 for `rio ps -q` found while reviewing the new CLI specs.

**Comment by izaac** [comment]
@StrongMonkey  `rio ps -a drop header` 

This requirement would only output the different objects like services/routes/domains but it will make it hard to read this without headers. It is already not that clear because even though these objects are grouped by type in the output there's no indication of what type each group is.

Sample output:

```bash
rio -A ps -a

NAME           IMAGE                      ENDPOINT                                                       SCALE     APP            VERSION    WEIGHT    CREATED             DETAIL
keen-joliot2   sangeetha/testupgrade:v1   https://keen-joliot2-5a7e52e0-default.ct8uct.on-rio.io:30217   1         keen-joliot2   5a7e52e0   100%      About an hour ago

NAME                    URL                                                        OPTS      ACTION    TARGET
router/default/route1   https://route1-default.ct8uct.on-rio.io:30217/to-tsrv-v0             to        default/default/keen-joliot2,port=80

NAME      CREATED   TARGET

```

**Comment by izaac** [comment]
@davidnuzik the UI makes sense for the new features and refactoring. I've opened an issue for one of the flags as it's failing but is not critical. Besides this [comment](https://github.com/rancher/rio/issues/429#issuecomment-547065824) I don't see anything major in the CLI. 

But this issue also covers a UI/CLI consistency check but that's not yet for 0.6.0, should we move this to the backlog and remove the `To Test` tag?

**Comment by davidnuzik** [comment]
Closing; the UI is TBD and to my knowledge there is nothing to test yet. When this becomes available then we can test and compare later.
