### ISSUE TITLE
Add endpoint to service object

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rio#43]
Steps:
1.  rio run -p 80/http -n test/psrv nginx
2.  rio inspect test/psrv

Results:  the endpoint isn't in the service object.  Be nice to be able to grab it from there for automation.

**Comment by StrongMonkey** [comment]
@ibuildthecloud should we show that?

**Comment by tfiduccia** [comment]
Version - v0.0.4-rc3
Verified added
