### ISSUE TITLE
Refactor Registry

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rio#430]
Details to be filled in.

**Comment by StrongMonkey** [comment]
- [ ] run buildkitd with runc builder

- [ ]  delete buildkit for dev

- [ ] remove hostpath mounts

- [ ] always push to registry

- [ ] no hostports on registry-proxy only socat

- [ ] add PV from storage class to registry (detect and use)

- [ ] run registry as a sidecar in buildkitd

**Comment by davidnuzik** [comment]
Already tested; should be good to go; closing.
