### ISSUE TITLE
build element naming

### ISSUE THREAD

**Issue by ibuildthecloud** [rancher/rio#433]
The names for the build element should change as follow (the yaml and CLI are should follow suit)

dockerFile -> dockerfile : This should include the full path of the Dockerfile.  Empty mean ${context} + "/Dockerfile"
dockerFilePath -> remove
buildContext -> context
buildArgs -> args
githubSecretName -> webhookSecret
gitSecretName -> pullSecret
pushRegistrySecretName -> pushRegistrySecret
buildImageName -> imageName
enablePr -> pr

**Comment by ibuildthecloud** [comment]
What is `push` for?

**Comment by StrongMonkey** [comment]
To be discussed. Need CLI or API review to decide what should be renamed exactly.

**Comment by cjellick** [comment]
Done as part of your API refactoring @ibuildthecloud

**Comment by rancher-max** [comment]
Confirmed nothing to QA here from a functionality perspective. 👍
