### ISSUE TITLE
Track deployed GVKs for generic manifest in stack

### ISSUE THREAD

**Issue by ibuildthecloud** [rancher/rio#437]

**Comment by cjellick** [comment]
if you remove a deployment from the riofile and rerun `rio up` we wont delete the deployement

**Comment by davidnuzik** [comment]
@StrongMonkey please update the issue body to be use-case based / explain at a high level.

**Comment by daxmc99** [comment]
The crux of this issue is that a Riofile can specify arbitrary k8s objects. These objects should be cleaned up if the same Riofile is applied with the k8 object removed. This mimics the beahvior of kubectl apply.

<details>
<summary>Example riofile</summary>
<br>
configs:
  conf:
    index.html: |-
      <!DOCTYPE html>
      <html>
      <body>
      
      <h1>Hello World</h1>
      
      </body>
      </html>
services:
  nginx:
    image: nginx
    ports:
    - 80/http
    configs:
    - conf/index.html:/usr/share/nginx/html/index.html

kubernetes:
    manifest: |-
        apiVersion: v1
        kind: Service
        metadata:
        name: redis-master
        labels:
            app: redis
            tier: backend
            role: master
        spec:
        ports:
        - port: 6379
            targetPort: 6379
        selector:
            app: redis
            tier: backend
            role: master
        ---
        apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
        kind: Deployment
        metadata:
        name: redis-master
        spec:
        selector:
            matchLabels:
            app: redis
            role: master
            tier: backend
        replicas: 1
        template:
            metadata:
            labels:
                app: redis
                role: master
                tier: backend
            spec:
            containers:
            - name: master
                image: k8s.gcr.io/redis:e2e  # or just image: redis
                resources:
                requests:
                    cpu: 100m
                    memory: 100Mi
                ports:
                - containerPort: 6379
        ---
        apiVersion: v1
        kind: Service
        metadata:
        name: redis-slave
        labels:
            app: redis
            tier: backend
            role: slave
        spec:
        ports:
        - port: 6379
        selector:
            app: redis
            tier: backend
            role: slave
        ---
        apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
        kind: Deployment
        metadata:
        name: redis-slave
        spec:
        selector:
            matchLabels:
            app: redis
            role: slave
            tier: backend
        replicas: 2
        template:
            metadata:
            labels:
                app: redis
                role: slave
                tier: backend
            spec:
            containers:
            - name: slave
                image: gcr.io/google_samples/gb-redisslave:v1
                resources:
                requests:
                    cpu: 100m
                    memory: 100Mi
                env:
                - name: GET_HOSTS_FROM
                value: dns
                # If your cluster config does not include a dns service, then to
                # instead access an environment variable to find the master
                # service's host, comment out the 'value: dns' line above, and
                # uncomment the line below:
                # value: env
                ports:
                - containerPort: 6379
        ---
        apiVersion: v1
        kind: Service
        metadata:
        name: frontend
        labels:
            app: guestbook
            tier: frontend
        spec:
        # if your cluster supports it, uncomment the following to automatically create
        # an external load-balanced IP for the frontend service.
        # type: LoadBalancer
        ports:
        - port: 80
        selector:
            app: guestbook
            tier: frontend
        ---
        apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
        kind: Deployment
        metadata:
        name: frontend
        spec:
        selector:
            matchLabels:
            app: guestbook
            tier: frontend
        replicas: 3
        template:
            metadata:
            labels:
                app: guestbook
                tier: frontend
            spec:
            containers:
            - name: php-redis
                image: gcr.io/google-samples/gb-frontend:v4
                resources:
                requests:
                    cpu: 100m
                    memory: 100Mi
                env:
                - name: GET_HOSTS_FROM
                value: dns
                # If your cluster config does not include a dns service, then to
                # instead access environment variables to find service host
                # info, comment out the 'value: dns' line above, and uncomment the
                # line below:
                # value: env
                ports:
                - containerPort: 80
</details>

**Comment by StrongMonkey** [comment]
Available to test in v0.6.0-alpha3.

**Comment by izaac** [comment]
@daxmc99 im getting the following with the provided `Riofile` test file.

```bash
rio up -f ./Riofile
FATA[0000] yaml: line 12: mapping values are not allowed in this context
```

**Comment by daxmc99** [comment]
Repo used for the creation of services:
https://github.com/daxmc99/rio-demo/tree/track_gvk
Repo used for deletion:
https://github.com/daxmc99/rio-demo/tree/track_gvk_drop_k8_manifests

**Comment by daxmc99** [comment]
Relevant PR is here https://github.com/rancher/rio/pull/643

**Comment by izaac** [comment]
We also need to make sure these objects are reflected using `rio export` after creating a stack using `Riofile`

`rio export stack/xxxx` 

@daxmc99 started working on https://github.com/rancher/rio/issues/641 which is basically this use case.

Right now we're basically just exporting this:

```yaml
apiVersion: rio.cattle.io/v1
kind: Stack
metadata:
  creationTimestamp: "2019-11-06T21:55:40Z"
  generation: 2
  name: riofile-test
  namespace: default
  resourceVersion: "128199"
  selfLink: /apis/rio.cattle.io/v1/namespaces/default/stacks/riofile-test
  uid: 2c73d7ee-00e0-11ea-a47c-42010aa8001a
spec:
  additionalGroupVersionKinds:
  - Group: ""
    Kind: Service
    Version: v1
  - Group: apps
    Kind: Deployment
    Version: v1
  - Group: ""
    Kind: Service
    Version: v1
  - Group: apps
    Kind: Deployment
    Version: v1
  - Group: ""
    Kind: Service
    Version: v1
  - Group: apps
    Kind: Deployment
    Version: v1
  - Group: ""
    Kind: ConfigMap
    Version: v1
  - Group: rio.cattle.io
    Kind: Service
    Version: v1
status: {}
```

**Comment by izaac** [comment]
I've tested this with the following kinds:

- Deployment
- Service
- ConfigMap
- Ingress

All these were created when defined in a Riofile or deleted if it existed in the cluster and was removed from the Riofile and then done a `rio up`

Working as expected in `rio v0.6.0-alpha.3`
