### ISSUE TITLE
don't default to all namespaces

### ISSUE THREAD

**Issue by ibuildthecloud** [rancher/rio#449]
It's a bit annoying to default to all namespaces.  We should just add the ability to set a ENV_VAR to default to all namespaces.

**Comment by cjellick** [comment]
or a flag `--all-namespaces`?

**Comment by izaac** [comment]
We default to `default` namespace in `v0.6.0-alpha.1` 
There's also a flag to specify a namespace `--namespace/-n` 
And there's also the `--all-namespaces/-A` to show objects from all namespaces.

This was validated as part of https://github.com/rancher/rio/issues/429
