### ISSUE TITLE
Registry proxy is not starting

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rio#453]
Version: v0.5.0-alpha.1

Registry proxy is not started during rio install. Build will fail by default if pushed into local registry.

**Comment by cbron** [comment]
Reproduction steps: 
* start rio on fresh cluster, wait for it to finish initializing
* see that pod `registry-proxy-...` doesn't exist in namespace `rio-system`
* you can also attempt to run a container via `rio run --name example https://github.com/rancher/rio-demo` and you will get an error: `no available registry endpoint: failed to do request: Head http://localhost:5442....`

Testing fix: 
* start rio on fresh cluster, wait for it to finish initializing
* notice that `registry-proxy` pod exists in namespace `rio-system`
* start and run a service without error via `rio run --name example https://github.com/rancher/rio-demo`

**Comment by StrongMonkey** [comment]
Tested with v0.5.0-alpha.2, the issue is solved.
