### ISSUE TITLE
Enforce the minimum cluster requirements by not installing rio if the cluster doesn't meet them

### ISSUE THREAD

**Issue by izaac** [rancher/rio#470]
Currently there's only a warning if rio detects a cluster doesn't meet the minimum installation requirements but rio will proceed with the installation.

`$ rio install`
`
Warning: detecting that your cluster doesn't have at least 3 GB of memory in total. Please try to increase memory for your nodes 
`

We shouldn't allow the installation to continue if the minimum requirements are not met by the cluster.

**Comment by davidnuzik** [comment]
Based on a discussion we think what we have today is acceptable. Closing.
