### ISSUE TITLE
workload run in Specific project?

### ISSUE THREAD

**Issue by chaets** [rancher/rio#472]
When I run rio run command it always run the workload in default project,
`rio run -p 9090/http --name test1 <image name>:latest:v0`

 now my question is when I need to run any workload in specific project other than default what keyword or flag  we need to use with rio run in rancher

**Comment by StrongMonkey** [comment]
@chaets You can run with --name ${namespace}/name to change to other namespace.

**Comment by chaets** [comment]
@StrongMonkey  I am not talking about namespace, I talking about the project, that has different different namespaces.
Like I have insights-ihies as project under insight cluster
![Screen Shot 2019-09-19 at 12 58 01 PM](https://user-images.githubusercontent.com/34632582/65268662-3e569500-dadd-11e9-8fe8-d075aa13fe8e.png)

**Comment by StrongMonkey** [comment]
If you follow the command and create workload under a different namespace, if that is included in your project, then it will show up in that project. Right now in rio you can't point your workload to a rancher project as there is no relationship between rancher concept and rio.

**Comment by davidnuzik** [comment]
Closing based on answer provided. You'll need to move any namespaces to your project in Rancher as needed.
