### ISSUE TITLE
memory hard limit is giving me memory reservation error

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rio#48]
steps:
1.  rio run -n tstack2/tservice1 --memory-limit 50[g]

results:  FATA[0000] failed to parse --memory-reservation: invalid size: '50[g]'.  I should be getting a --memory-limit error not a --memory-reservation error.

**Comment by StrongMonkey** [comment]
@tfiduccia the correct format should be `--memory-limit 50g`(without brackets)

**Comment by tfiduccia** [comment]
@StrongMonkey  - yes I know.  This is not about it not working.  It's about the error being wrong.

**Comment by StrongMonkey** [comment]
available to test on v0.0.4-rc1.

**Comment by tfiduccia** [comment]
Version - v0.0.4 rc1
Verified fixed
