### ISSUE TITLE
Publicdomain failed to request letsencrypt certificates if pointing to router

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rio#481]
Version: v0.5.0-alpha.2

Steps to reproduce:

Register foo.bar domain to router
`Rio domain register foo.bar router`

Access https://foo.bar
Letsencrypts certs fail to provision.

**Comment by cbron** [comment]
Testing instructions: 

1. create a router to point to a service
2. create a public domain, change the dns record cname point to cluster domain in rio. (xxx.on-rio.io showing up in rio info)
3. rio domain register $domain $name_of_router
4. access that domain, it should be trusted as we requested a certs for that public domain.

**Comment by StrongMonkey** [comment]
Available to test in v0.5.0-alpha.3.

**Comment by StrongMonkey** [comment]
@cbron I use the follow instruction to test:
1. Create a GKE cluster and install rio. GKE will expose a loadbalancer that has a public IP on it.
2. Create a service service-foo and router router-foo following the docs.
3. Create two custom domains(I did this in DO space) to map CNAME record to rio cluster domain.
4. Use `rio domain register` to register domain to service-foo and router-foo.
5. Make sure you can access your services and routers by that public domain, and also certs are provisioned for those domains.

**Comment by cbron** [comment]
Working correctly in alpha3

```
$ rio run --name demo1 https://github.com/rancher/rio-demo
$ rio ps

NAME            CREATED          ENDPOINT                                 REVISIONS   SCALE     WEIGHT    DETAIL
default/demo1   3 minutes ago   https://demo1-default.zsak9z.on-rio.io   v0          1         100%

$ rio route add x.default to default/demo1
$ rio route

NAME          URL                                    OPTS      ACTION    TARGET
default/x     https://x-default.zsak9z.on-rio.io               to        demo1,port=80

$ rio domain register caleb.do.rancher.space default/x
$ rio domain register caleb2.do.rancher.space default/x
$ rio domain

NAME                      DOMAIN                   TARGET
default/caleb-do--7bff2   caleb.do.rancher.space   default/x
default/caleb2-do-2b467   caleb2.do.rancher.space   default/x

$ curl https://caleb.do.rancher.space
Hello World

$ openssl s_client -connect caleb.do.rancher.space:443

Certificate chain
 0 s:/CN=*.zsak9z.on-rio.io
   i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
....
```
