### ISSUE TITLE
Promoting a new revision the parent service URL still redirects to the old revision

### ISSUE THREAD

**Issue by izaac** [rancher/rio#485]
Steps:

- `rio run --scale 2 -p 80 -n appone  sangeetha/testupgrade:v2`
   - Got `appone:v0` created and the parent ENDPOINT for the service.
- `rio stage --image sangeetha/testupgrade:v3 default/appone`
  - Got a new revision for appone with its own endpoint and WEIGHT =0 
  - Parent ENDPOINT still same, `curl`ing the parent endpoint still gets `appone:v0`
- `rio promote default/appone:<new revision>`
  - the new revision starts rolling out, increasing its weight
- New appone revision gets 100% WEIGHT, but parent ENDPOINT still reaching revision `v0` `testupgrade:v2` contents..

GKE Cluster v1.14.6-gke.1 
Default install `linkerd`

**Comment by StrongMonkey** [comment]
Available to test in v0.5.0-alpha.3.

**Comment by izaac** [comment]
This is working now in `v0.5.0-alpha.3`. 

- Using `istio` mesh mode
- Using `linkerd` mesh mode
