### ISSUE TITLE
In -h results (default: []) is showing up when it shouldn't

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rio#49]
Steps:
1.  rio run -h or rio create -h

Results:
(default: []) is showing up in the explanation for a lot of the fields and this is not useful info.  Shouldn't really be there.

**Comment by vincent99** [comment]
Some are `map[]` too.

**Comment by StrongMonkey** [comment]
available to test on v0.0.4-rc1.

**Comment by tfiduccia** [comment]
Version - v0.0.4 rc1
verified fixed
