### ISSUE TITLE
Rollout controller

### ISSUE THREAD

**Issue by daxmc99** [rancher/rio#496]
Per 
https://github.com/rancher/rio/blob/api-refactor/pkg/apis/rio.cattle.io/v1/service_types.go#L109
We need to have a controller that performs the rollout. 

This controller should work to make the desiredWeight and ActualWeight equivalent. 
It will use the increment and interval values to update the weights. Previously this was done with the appweight controller.

Also needs to respect the pause field:
https://github.com/rancher/rio/blob/api-refactor/pkg/apis/rio.cattle.io/v1/service_types.go#L55 

Merge to refactor branch

**Comment by davidnuzik** [comment]
Needs general regression testing again against rollout/promotion/weight.

**Comment by rancher-max** [comment]
v0.6.0-alpha.1 has known promotion bug: Running a simple `rio promote [service name]` gives the following error:
```
demo-v3 promoted
FATA[0000] Service.rio.cattle.io "demo" is invalid: spec.rollout.interval: Invalid value: "string": spec.rollout.interval in body must be of type object: "string", Service.rio.cattle.io "demo-v3" is invalid: spec.rollout.interval: Invalid value: "string": spec.rollout.interval in body must be of type object: "string" 
```

The spec of the service is:
```
spec:
  app: demo
  image: ibuildthecloud/demo:v3
  imagePullPolicy: IfNotPresent
  ports:
  - port: 80
    protocol: HTTP
    targetPort: 80
  version: v3
  weight: 0
```

After try8ing with setting increment and interval (`rio promote --increment 5 --interval 5 demo-v3`), I get the same error and same spec.

Continuing ideas:
```
rio run --rollout-interval="5" --rollout-increment="5" -n test --version v1 -p 80/http ibuildthecloud/demo:v1
FATA[0000] Service.rio.cattle.io "test" is invalid: spec.rollout.interval: Invalid value: "string": spec.rollout.interval in body must be of type object: "string" 
```
where the value after `--rollout-interval` and `--rollout-increment` was tried with quotes and without

**Comment by cbron** [comment]
Ready to test in v0.6.0-alpha2. Try quite a few combinations of interval/increment.

**Comment by rancher-max** [comment]
Working in v0.6.0-alpha.2. Setting interval to 0s causes immediate rollout.
