### ISSUE TITLE
SMI Update controller

### ISSUE THREAD

**Issue by daxmc99** [rancher/rio#497]
The SMI controller is required to update the gateway and service mesh controlplanes with the actual weight values of the various services and create the routes correctly for the gateway. 

It will need to work for:
- Linkerd
- Istio

Istio types needs to be updated, as well as updating the SMI implementation for Linkerd. 

Merge to api-refactor branch

**Comment by davidnuzik** [comment]
With the change to gloo and dropping Istio this issue is no longer needed. Closing.
