### ISSUE TITLE
Miscellaneous API Changes

### ISSUE THREAD

**Issue by daxmc99** [rancher/rio#499]
Implement necessary renaming from https://github.com/rancher/rio/tree/api-refactor

Examples:
* The expose boolean on ContainerPort needs to be respected on both Istio and DNS
https://github.com/rancher/rio/blob/b37c668498525f0991262c184f183308cb799b1b/pkg/apis/rio.cattle.io/v1/service_types.go#L299

* Also autoscale renaming
https://github.com/rancher/rio/compare/api-refactor#diff-cc3e4dfcefb6769c6b060ff7df2f7b63R40
https://github.com/rancher/rio/compare/api-refactor#diff-cc3e4dfcefb6769c6b060ff7df2f7b63R43

Merge to api-refactor branch

**Comment by davidnuzik** [comment]
No longer relevant with new api refactor; closing this issue.
