### ISSUE TITLE
CLI changes

### ISSUE THREAD

**Issue by daxmc99** [rancher/rio#500]
Necessary cli changes to implement changes due to new types

Rollout controller:
https://github.com/rancher/rio/issues/496
SMI weight update controller:
https://github.com/rancher/rio/issues/497
Multi-repo and image builder changes:
https://github.com/rancher/rio/issues/498
API renaming
https://github.com/rancher/rio/issues/499

Merge to api-refactor branch

**Comment by cbron** [comment]
I think we can close this because it's included within all our other tickets.

**Comment by rancher-max** [comment]
Agree. And it's a bit different now since two of them were closed as not needed, and #498 really applies to Riofile with example1 and example2 is invalid.
