### ISSUE TITLE
Grafana installation is stuck in lite install with mesh mode istio

### ISSUE THREAD

**Issue by izaac** [rancher/rio#507]
**Describe the bug**
Install with `rio install --lite --mesh-mode istio`

I've waited for the installation to finish for 20 minutes.

`/ Waiting for all the system components to be up. Not ready: [grafana]`

**To Reproduce**
1. Setup a GKE cluster I used v1.14.6-gke.1 as k8s version.
2. Install rio using `rio install --lite --mesh-mode istio`

**Expected behavior**

Finish the install of all rio lite mode features using `--lite` and `--mesh-mode istio`

**Kubernetes version & type (GKE, on-prem)**: `kubectl version`
```
v1.14.6-gke.1
```
Type:
**Rio version**: `rio info`
```
Rio Version: v0.5.0-alpha.3 (cdb631d1)
Rio CLI Version: v0.5.0-alpha.3 (cdb631d1)
Cluster Domain: <domain>.on-rio.io
Cluster Domain IPs: X.X.X.X
System Namespace: rio-system

System Components:
activator status: running
autoscaler status: running
build-controller status: running
buildkitd-dev status: running
cert-manager status: running
controller status: running
gateway status: running
istio-citadel status: running
istio-pilot status: running
istio-sidecar-injector status: running
istio-telemetry status: running
kiali status: running
prometheus status: running
registry status: running
webhook status: running
```
**Additional context**
`rio systemlog`
output:
```
No output
```

**Comment by StrongMonkey** [comment]
@izaac available to test in v0.5.0-alpha.4

**Comment by izaac** [comment]
@StrongMonkey 

Now after this change using v0.5.0-alpha.4:
`rio install --mesh-mode istio`

```
Deploying Rio control plane....
\ Waiting for all the system components to be up. Not ready: [mixer]
```

The installation just sits there. I gave up after 12 minutes.

These other installation combinations worked: 

`rio install --lite --mesh-mode istio` ✅ 
`rio install --lite --mesh-mode linkerd` ✅ 
`rio install ` ✅

**Comment by izaac** [comment]
Above installation combinations are now working as expected using v0.5.0-alpha.4 🥇 

Closing.
