### ISSUE TITLE
Retrieve the public IP from infrastructure providers like Linode to use it for ClusterDomain in hostport mode

### ISSUE THREAD

**Issue by izaac** [rancher/rio#518]
**Describe the bug**

**To Reproduce**
1. Create a cluster from Rancher. I used rancher `master-head (v2.3) (09/25/2019)`
2. The nodes for worker, Control Plane, and etcd all had Internal and External IPs in Rancher.
3. Cluster Domain picked the Worker node Internal IP instead of the external.

I had to reinstall rio using: `rio install --ip-address ${ip_address} --mode hostport` to use the external IP explicitly. 

**Expected behavior**

Rio obtaining the external IP from the Cluster Worker nodes should be the default.

**Kubernetes version & type (GKE, on-prem)**: `kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}

Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:55Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
Type:
**Rio version**: `rio info`
```
v0.5.0-alpha.5
```

**Comment by cjellick** [comment]
public ip must be set on k8s node and then this should work

**Comment by izaac** [comment]
@ibuildthecloud as discussed today having the internal ip address checked while creating the linode cluster in this case makes rio to use the internal ip addresses for setting up the cluster domain.

If I don't choose that option I don't have to do that as the Linode nodes will end up having the external ip address and rio will use those to build the dns endpoints.

@cjellick @davidnuzik  I'm just wondering what are the next steps from here. Rancher's Linode node template has the `Add a Private IP` as default.

**Comment by davidnuzik** [comment]
Try with cloud-provider option (YAML)

**Comment by izaac** [comment]
With cloud provider even if the VMs are configured with **both** external and internal IP addresses the rio cluster domain IP is using the external

I've tested this with `rio v0.5.0` on Linode by generating the basic rke Yaml configuration for `cloud_provider: external` and a custom cluster with Azure as cloud provider.

@cjellick @StrongMonkey @davidnuzik

**Comment by cjellick** [comment]
What did you use to deploy the linode cloud provider? like what did your full yaml look like for that

**Comment by cjellick** [comment]
to be more clear, just "external" isnt enough

**Comment by izaac** [comment]
@cjellick I followed a combination of linode documentation, I can share you the full yaml tomorrow but it was basically a combination of doing this:

https://github.com/linode/linode-cloud-controller-manager
```
Example:

./deploy/generate-manifest.sh $LINODE_API_TOKEN us-east
```

> This will create a file ccm-linode.yaml which you can use to deploy the CCM.
> You would then take the contents of that file and add it to the YAML under RKE add-ons in create cluster, making sure to specify cloud provider as external.

And some instructions from this old cached article (specifically the yaml part as there's a Linode driver):

https://webcache.googleusercontent.com/search?q=cache:ZV47sknxJ-wJ:https://www.linode.com/docs/applications/containers/kubernetes/how-to-deploy-kubernetes-on-linode-with-rancher-2-2/+&cd=6&hl=en&ct=clnk&gl=us

Of course when I wrote "external" I was implying the above.

**Comment by izaac** [comment]
@cjellick For Azure it was more straightforward as its external cloud_provider configuration is well integrated in the Rancher UI and was also suggested by @StrongMonkey to do the test with it as the Linode documentation is not that clear.

After doing the Linode test I also validated Azure anyways.

**Comment by izaac** [comment]
In Linode I faced some issues with the addon pods getting properly setup with RKE but using the Azure cluster import with cloud_provider external this is working as expected. rio is using the node's external IP's to configure the Cluster Domain.

Internal IPs are not used as expected for the Cluster Domain, checked by using `rio info` after a `rio install --mode hostport`

**Comment by izaac** [comment]
This is the Linode issue for reference.
https://github.com/rancher/rancher/issues/23446
