### ISSUE TITLE
rio run --cidfile should be changed or dropped

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rio#53]
Steps:
1.  rio run -h

Results:  Under options:    
--cidfile value               Write the container ID to the file

Comment: This doesn't make sense in this current context so we need to either drop it or change it.

**Comment by StrongMonkey** [comment]
available to test on v0.0.4-rc1.

**Comment by tfiduccia** [comment]
Version - v0.0.4 rc5
Verified fixed
