### ISSUE TITLE
Rio uninstall doesn't clean up mutatingwebhookconfigurations

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rio#543]
We don't clean up mutatingwebhookconfigurations today, which make it really hard to switch between linkerd and istio.

**Comment by StrongMonkey** [comment]
This is the mutatingwebhookconfigurations come from istio and linkerd, which does sidecar injection.

**Comment by cbron** [comment]
Confirmed that this bug doesn't exist on linkerd, it only affects istio. Therefore we will not pursue a fix.
