### ISSUE TITLE
Scale is not going above 10 when a range is given

### ISSUE THREAD

**Issue by rancher-max** [rancher/rio#545]
**Describe the bug**
Service is not scaling above 10 pods when a range above 10 is given. Upon inspection, the spec.maxScale and spec.minScale values are properly set in the CRD, but the actual scale and pod count only goes to 10.

**To Reproduce**
1. `rio run --scale=1-20 -n autoscale strongmonkey1992/autoscale:v0`
    - can set the scale to as low as you want and anything above 10. (validated with `scale=9-11`)
2. `rio inspect autoscale`
    - shows `maxScale` and `minScale` values in the resulting yaml as what they were set to in the run command.
3. `hey -z 3m -c 200 http://autoscale-default.<cluster domain>:9080`
    - while this is running, `watch rio ps` and should see the scale on the default/autoscale service increasing. With the amount of Requests per Second, I would expect this value to go above 10, but it does not.

**Expected behavior**
The SCALE should go above 10 at some point when doing autoscaling with a given range.

**Kubernetes version & type (GKE, on-prem)**: `kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-19T13:57:45Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-gke.2", GitCommit:"c9de33b5439df6e206d7ba646787c6ace92d737b", GitTreeState:"clean", BuildDate:"2019-09-06T18:30:33Z", GoVersion:"go1.12.9b4", Compiler:"gc", Platform:"linux/amd64"}
```
Type:
**Rio version**: `rio info`
```
Rio Version: v0.5.0 (303f3652)
Rio CLI Version: v0.5.0 (303f3652)
Cluster Domain: x.on-rio.io
Cluster Domain IPs: x.x.x.x
System Namespace: rio-system

System Components:
activator status: running
autoscaler status: running
build-controller status: running
buildkitd-dev status: running
cert-manager status: running
controller status: running
gateway status: running
istio-pilot status: running
registry status: running
webhook status: running
```
**Additional context**
`rio systemlogs`
output:
There are a lot of similar attempts here, but here's the results after running the above steps:
```
rio-controller | time="2019-10-02T22:23:29Z" level=info msg="Setting desired scale 9 for default/autoscale"
rio-controller | time="2019-10-02T22:24:39Z" level=info msg="Setting desired scale 10 for default/autoscale"
rio-controller | time="2019-10-02T22:28:59Z" level=info msg="Setting desired scale 9 for default/autoscale"
```

**Comment by cbron** [comment]
https://github.com/knative/serving/blob/9162139d768af9e2463ab007a43c385ae47ba90d/config/config-autoscaler.yaml#L106-L113

https://github.com/rancher/rio/blob/master/stacks/rio-autoscaler-stack.yaml#L4

@StrongMonkey @ibuildthecloud since we have a default max-scale of 10 on podautoscalers already, maybe we up that guy to 1k ? Otherwise the CLI flag is basically useless.

**Comment by StrongMonkey** [comment]
@cbron well shoot! we should bump that.

**Comment by cbron** [comment]
Actually on second look I wonder if this is actually a bug with our setup and the tick-interval, it's supposed to go up by 10 per tick-interval. But in my tests if you have max-scale-up-rate of 3 and 2 existing pods it scales to 3, when really it should go to 6. Needs more debugging. But for now if we just up the max the autoscaler should manage it.

**Comment by rancher-max** [comment]
Tested in v0.6.0-alpha.1 and the issue is resolved.
