### ISSUE TITLE
Fix autoscalers incorrect metrics

### ISSUE THREAD

**Issue by cbron** [rancher/rio#547]
Follow up from issue: https://github.com/rancher/rio/issues/545

Determine why autoscaler thinks we are always at 0 scale, and why we enter panic mode immediately regardless of panic settings. Think it has something to do with our forks custom CRD's. End goal is that we can lower `max-scale-up-rate` back to 10 and have it be a governor again.

**Comment by davidnuzik** [comment]
Execute auto-scaling tests again; ensure working as expected.
