### ISSUE TITLE
Add note to documentation for rio installs in clusters not using cloud_provider 

### ISSUE THREAD

**Issue by izaac** [rancher/rio#561]
**Describe the bug**

Documentation Improvement:

When installing rio in Infrastructure providers like azure, the internal IP address is used to setup the Cluster Domain.

These Infrasctructure providers like Linode, Azure, etc. may use internal IP addresses along with external IPs in their VMs This causes rio to use the internal IP address to setup the Cluster Domain.

`rio install --mode hostport`

**To Reproduce**
Reference issue: https://github.com/rancher/rio/issues/518

**Expected behavior**
Cluster should use `cloud_provider` when spinning up a new cluster if the VMs are using internal IPs or Use external IPs only.

Type:
**Rio version**: `rio info`
```
v0.5.0
```

**Comment by izaac** [comment]
I just finished validating in Linode using `cluster_provider` rio use the external IPs to setup the Cluster Domain, even if the VMs had private IPs.

https://www.linode.com/docs/applications/containers/kubernetes/how-to-deploy-kubernetes-on-linode-with-rancher-2-x/#deploy-a-kubernetes-cluster

The Linode addon yaml has an error in the tolerations but we're in the process of notifying Linode of this issue.

I still think we should add at least a note in the Docs to let the users know they need follow the specific `cloud_provider` configuration for their provider.

@davidnuzik @StrongMonkey @cjellick

**Comment by izaac** [comment]
Linode issue for reference: https://github.com/rancher/rancher/issues/23446

**Comment by cbron** [comment]
Added note in docs, closing.
