### ISSUE TITLE
gopkg.yaml/v2  CVE

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rio#563]
We need to bump gopkg.in/yaml.v2  due the a CVE found in kubernetes. 

https://github.com/kubernetes/kubernetes/issues/83253

https://github.com/go-yaml/yaml/commit/f221b8435cfb71e54062f6c6e99e9ade30b124d5

**Comment by daxmc99** [comment]
Fixed in this commit
https://github.com/rancher/rio/blob/ac038a30ec1c2c6a8e373b2b495d4815c88e1773/go.mod#L85

Verified that go.mod points to `gopkg.in/yaml.v2 v2.2.4`
