### ISSUE TITLE
Rolling out staged revision using rio weight uses its initial spec value for the first rollout interval

### ISSUE THREAD

**Issue by rancher-max** [rancher/rio#577]
**Describe the bug**
Trying to rollout a revision using `rio weight` with the `--rollout-increment` flag does not honor the value set for the first tick of rollout. 

Rolling back the first revision using the same command DOES honor the increment value on the first tick, so this only applies to the staged revision.

**To Reproduce**
1. Run a service: `rio run -n test -p 80/http ibuildthecloud/demo:v1`
2. Stage a service: `rio stage --image ibuildthecloud/demo:v3 default/test:v3`
3. Rollout the staged service: `rio weight --rollout=true --rollout-increment=10 --rollout-interval=5 default/test:v3=80` and be watching the output of `rio ps`. 

It will initially change the weights to 95%,5% instead of the expected 90%,10%. The second tick will go to 85%,15%, so at that point the increment is being honored.

**Expected behavior**
The rollout increment should be honored for every tick of the rollout. The values after the first rollout tick with a rollout-increment of 10 should be 90%,10%.

**Kubernetes version & type (GKE, on-prem)**: `kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-19T13:57:45Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4-k3s.1", GitCommit:"a7531b1ab3fd5ff987b074472ddfb84a2f5326bc", GitTreeState:"clean", BuildDate:"2019-09-19T22:36Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
Type:
**Rio version**: `rio info`
```
Rio Version: v0.5.0 (303f3652)
Rio CLI Version: v0.5.0 (303f3652)
Cluster Domain: xxxxxx.on-rio.io
Cluster Domain IPs: x.x.x.x
System Namespace: rio-system

System Components:
activator status: running
autoscaler status: running
build-controller status: running
buildkitd-dev status: running
cert-manager status: running
controller status: running
gateway status: running
istio-pilot status: running
registry status: running
webhook status: running
```
**Additional context**
Nothing in systemlogs.

**Comment by cbron** [comment]
Ready to test in v0.6.0-alpha2.

**Comment by rancher-max** [comment]
Working in v0.6.0-alpha.2
