### ISSUE TITLE
Annotations are not copied when staging a new version.

### ISSUE THREAD

**Issue by r2ewj** [rancher/rio#579]
**Background:**

Since moving to Linkerd I have to add an annotation for services that connect to our MySQL db on a non standard port:
config.linkerd.io/skip-outbound-ports: "4006"
Without this annotation connections to the DB timeout.  I added the annotation after reading this article:
https://linkerd.io/2/features/protocol-detection/

**Reproduce:**

So, if I deploy a service using the following rio command the service works fine:

rio run -n jwt/verify --image-pull-policy=always --annotations="config.linkerd.io/skip-outbound-ports=4006" [LOCAL_DOCKER_REPO]/jwt-verify

However if I update the image, and stage a new version my annotation isn't copied over and the staged version will timeout until I manually add the annotation.

rio inspect jwt/verify:v0
---
apiVersion: rio.cattle.io/v1
kind: Service
metadata:
  annotations:
    config.linkerd.io/skip-outbound-ports: "4006"
  creationTimestamp: "2019-10-18T15:55:56Z"
  ...........

 rio stage jwt/verify
jwt/verify:v33240

rio inspect jwt/verify:v33240
---
apiVersion: rio.cattle.io/v1
kind: Service
metadata:
  creationTimestamp: "2019-10-18T15:58:10Z"
  finalizers:
  ......

Please let me know if there's any additional information I can provide that would be useful.

Thanks!

**Comment by rancher-max** [comment]
@r2ewj there's a workaround you can use in the meantime for staging services that have these custom annotations. You can also use this if you're adding custom labels, as it has the same issue.

`rio run -n jwt/verify-v2 --version v2 --app verify --weight 0 --image-pull-policy=always --annotations="config.linkerd.io/skip-outbound-ports=4006" [LOCAL_DOCKER_REPO]/jwt-verify`

Note the value after `-n` should be unique with each new version, and the --version flag is optional but nice to have.

**Comment by izaac** [comment]
Validated in latest `rio v0.6.0-alpha.3` staging a service now preserves annotations metadata.
