### ISSUE TITLE
Error installing rio on k8s v1.16.2

### ISSUE THREAD

**Issue by greyarch** [rancher/rio#580]
**Describe the bug**
`rio install` fails when using k8s v1.16.2.
Error message is `failed to discover client for extensions/v1beta1, Kind=Deployment`

**To Reproduce**
Create a k8s v1.16.2 cluster. Try installing rio.

**Expected behavior**
Rio gets isntalled.

**Kubernetes version & type (GKE, on-prem)**: `kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by StrongMonkey** [comment]
@greyarch  thanks for reporting this. We should bump api version for deployment in next release.

**Comment by izaac** [comment]
Validated that this fails with k8s 1.16.2 using `k3s v0.10.0-rc2` 
@StrongMonkey @davidnuzik

**Comment by davidnuzik** [comment]
Thanks @izaac moving out of test.

**Comment by Vad1mo** [comment]
Is there any workaround or pre-release available meanwhile?

**Comment by izaac** [comment]
@Vad1mo we are expecting to have a v0.6.0 RC soon.

**Comment by izaac** [comment]
@Vad1mo latest `v0.6.0-alpha.1` is out, but expect it to contain bugs. It works with k8s 1.16.2

**Comment by izaac** [comment]
I tested this with a k3s v0.10.0 instance on Linode, the installation goes through with rio despite the warning messages.

I did the same in a local docker installation using k3d

`k3d create --workers 0 --image rancher/k3s:v0.10.0 -n $name  --publish 80:80 --publish 443:443 --publish 9443:9443 --publish 9080:9080 &&`

```bash
rio install  --ip-address=127.0.0.1
Deploying Rio control plane....
- Warning: Detected that Rio cluster domain is not generated for this cluster right nowClusterDomain is reachable. Run `rio info` to get more info.
rio controller version v0.6.0-alpha.1 (7678d67d) installed into namespace rio-system
Controller logs are available from `rio systemlogs`

Welcome to Rio!

Run `rio run https://github.com/rancher/rio-demo` as an example
➜  rio-izaac git:(master) ✗ rio info
Rio Version: v0.6.0-alpha.1 (7678d67d)
Rio CLI Version: v0.6.0-alpha.1 (7678d67d)
Cluster Domain: fn5f8w.on-rio.io
Cluster Domain IPs: 127.0.0.1
System Namespace: rio-system
System Ready State: false
Wildcard certificates: false

System Components:

➜  rio-izaac git:(master) ✗ k cluster-info
Kubernetes master is running at https://127.0.0.1:6443
CoreDNS is running at https://127.0.0.1:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
➜  rio-izaac git:(master) ✗ k version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2-k3s.1", GitCommit:"b8b17ba55f20e590df507fce333dfee13ab438c6", GitTreeState:"clean", BuildDate:"2019-10-16T05:17Z", GoVersion:"go1.13.3", Compiler:"gc", Platform:"linux/amd64"}
```

The installation is being polished at the moment by Dev to address all these and we will be further test it in a future alpha/RC. The original reported issue of not being able to install in a k8s cluster v1.16.2 cluster seems solved.

**Comment by izaac** [comment]
Related issues for trakcing:

https://github.com/rancher/rio/issues/619
https://github.com/rancher/rio/issues/605

**Comment by Vad1mo** [comment]
can confirm as well that Installation works on 1.16.2
