### ISSUE TITLE
--expose setting host port on pod

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rio#61]
Steps:
1.  rio run -n tsk1/texpose --expose 22:80 nginx
2.  rio inspect --format '{{.id}}' tsk1/texpose | cut -f1 -d: #to get <namespace>
3.  rio kubectl get -n <namespace> -o=json deploy/texpose1

Results: Host port is filled out
![image](https://user-images.githubusercontent.com/11514927/46322761-8bc1b580-c59f-11e8-858c-9170fa176e36.png)

**Comment by StrongMonkey** [comment]
should be fixed in v0.0.4-rc1.

**Comment by tfiduccia** [comment]
Version - v0.0.4 rc1
Verified fixed
