### ISSUE TITLE
Allow logs to get any container state

### ISSUE THREAD

**Issue by cbron** [rancher/rio#614]
Ideally a user should be able to specify a container and see logs for all statuses (terminated, waiting and running). Stern doesn't seem to [allow this](https://github.com/wercker/stern/blob/08066e41d7b7c0a41b167021793434275ddb0466/stern/container_state.go), you have to pick one. We can improve and PR.

Update: Should have 2 options: terminated or running/waiting.

**Comment by cbron** [comment]
Would be good to address this as well: https://github.com/rancher/rio/issues/708

**Comment by rancher-max** [comment]
@cbron This looks like it only logs the pod from when starting to tail the logs and the next pod. If I then destroy the next pod, I don't see any output:

Log Tailing Output:
```sh
$ rio logs test+ default test-knh5p-57c8479bfc-v4bwt › test-knh5p
+ default test-knh5p-57c8479bfc-v4bwt › test-knh5p
+ default test-knh5p-57c8479bfc-k8gqr › test-knh5p
Error opening stream to default/test-knh5p-57c8479bfc-k8gqr: test-knh5p
: container "test-knh5p" in pod "test-knh5p-57c8479bfc-k8gqr" is waiting to start: PodInitializing
+ default test-knh5p-57c8479bfc-v4bwt › test-knh5p
Error opening stream to default/test-knh5p-57c8479bfc-v4bwt: test-knh5p
: container "test-knh5p" in pod "test-knh5p-57c8479bfc-v4bwt" is waiting to start: PodInitializing
+ default test-knh5p-57c8479bfc-k8gqr › test-knh5p
Error opening stream to default/test-knh5p-57c8479bfc-k8gqr: test-knh5p
: container "test-knh5p" in pod "test-knh5p-57c8479bfc-k8gqr" is waiting to start: PodInitializing
+ default test-knh5p-57c8479bfc-k8gqr › test-knh5p
+ default test-knh5p-57c8479bfc-v4bwt › test-knh5p
Error opening stream to default/test-knh5p-57c8479bfc-v4bwt: test-knh5p
: container "test-knh5p" in pod "test-knh5p-57c8479bfc-v4bwt" is terminated
```

Commands in order:
1. `rio rm pod/test-knh5p-57c8479bfc-v4bwt`
2. `rio rm pod/test-knh5p-57c8479bfc-k8gqr`
^^ That had no additional output in the tailed logs. I got the pod name from output in the tailed logs.

**Comment by cbron** [comment]
Interesting. Looks like that should work: https://github.com/rancher/stern/blob/master/stern/watch.go#L92-L111

Wanna open a 2nd ticket for that, it doesn't need to be in 0.6.0, its not a standard case
