### ISSUE TITLE
Save GVK on the stack object

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rio#622]
Save label on child object

So the UI can lookup child objects

**Comment by StrongMonkey** [comment]
Available to test in v0.6.0-alpha3. @izaac contact @daxmc99 for more detail to test.

**Comment by daxmc99** [comment]
cc @vincent99

**Comment by izaac** [comment]
This is directly related to the testing of: https://github.com/rancher/rio/issues/437 which is completed using `rio v0.6.0-alpha.3` but I would like to test this after https://github.com/rancher/rio/issues/641 is completed by Dev and ready for testing.

**Comment by izaac** [comment]
GVKs are getting now exposed using `rio export stack/<stack name>` I've tested with both local and github repo Riofiles.

Updating the Riofile with `rio up` and with proper permissions makes rio create the objects as k8s objects properly. This is also stored in the stack and can be viewed now using `rio export` default to yaml and also json with the `--format json` flag.

`rio up --name lts --permission "* apps/deployments" --permission "* services" -f ./Riofile`
`rio up --name ts --branch track_gvk --permission "* apps/deployments" --permission "* services" https://github.com/daxmc99/rio-demo`

Editing the Riofile and performing `rio up` to update the stack makes the proper changes both in rio and the objects in the k8s manifest in the stack and also `rio export` shows the stack changes.
