### ISSUE TITLE
Implement build command

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rio#624]
Need to finalize details; this is a placeholder for any general work required to implement and add the `build` command.

**Comment by StrongMonkey** [comment]
We are also going to add `rio image` command to show all the built images.

**Comment by StrongMonkey** [comment]
`rio build` is implemented in this https://github.com/rancher/rio/pull/669

**Comment by StrongMonkey** [comment]
`rio image` is implemented in this https://github.com/rancher/rio/pull/670

**Comment by StrongMonkey** [comment]
Available to test in v0.6.0-alpha3. @izaac Ping me on slack if you need more details.

**Comment by rancher-max** [comment]
`rio image` is working in v0.6.0-alpha.3. `rio build` is failing in some cases. See referenced issue above. In non-riofile case it seems to be working. Note that it is specific for local builds, so trying to specify a file from a remote github repo will fail.

**Comment by rancher-max** [comment]
Since there is an open issue to track the failing cases, mentioned above, and this is working in most cases, I believe we can close this enhancement for v0.6.0
