### ISSUE TITLE
Stats / Graphs for UI

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rio#638]
This issue is for tracking work for a UI we are internally working on.
This is internally tracked here https://github.com/rancherlabs/saasy/issues/32

**Comment by daxmc99** [comment]
Repo is up here https://github.com/daxmc99/prometheus-scraper 
Ready for review

**Comment by davidnuzik** [comment]
Moving to done. The expectation is that this is complete already; if this is not true please re-open and assign v0.6.x milestone. Tracked internally via https://github.com/rancherlabs/saasy/issues/32
