### ISSUE TITLE
Handle rio export

### ISSUE THREAD

**Issue by cbron** [rancher/rio#641]
Stack export should fetch objects, like namespace export does.:  https://github.com/rancher/rio/blob/ac038a30ec1c2c6a8e373b2b495d4815c88e1773/cli/cmd/export/export.go#L49-L51
Will likely need to update the riofile integration test. 
 
Also need a solution for edit: https://github.com/rancher/rio/blob/master/cli/cmd/edit/stack/stack.go

Finally, fix riofile export tests

**Comment by davidnuzik** [comment]
Possibly impacts other areas that may utilize template field.

**Comment by cbron** [comment]
If edit is non-trivial to update (ie we can't just reuse the export logic and call `up` again) bring up idea to wider group about removing stack edit and having people use the manual `export -> edit -> up` flow.

**Comment by cbron** [comment]
Ready to test in v0.6.0-alpha.5, ping me for questions

**Comment by izaac** [comment]
I've been trying to do a `rio up` with the default demo but also on @daxmc99's Riofile with k8s manifest but I'm not able to get the stack created somehow in alpha.5 @StrongMonkey :

I've tried testing this using the default Kubeconfig retrieved from a k3s cluster (copied from its master node) and a GKE cluster (using gcloud) without any RBAC users configuration.

`rio up --name teststack --branch track_gvk  https://github.com/daxmc99/rio-demo`

`rio logs <taskrun>` shows:

```
default-teststack-stack-629c5-dfbd1-pod-f00d95 step-rio-up time="2019-11-12T04:00:40Z" level=fatal msg="failed to create default/frontend apps/v1, Kind=Deployment for  default/teststack: deployments.apps is forbidden: User \"system:serviceaccount:default:default-teststack-stack-629c5-dfbd1-stack\" cannot create resource \"deployments\" in API group \"apps\" in the namespace \"default\", failed to create default/redis-master apps/v1, Kind=Deployment for  default/teststack: deployments.apps is forbidden: User \"system:serviceaccount:default:default-teststack-stack-629c5-dfbd1-stack\" cannot create resource \"deployments\" in API group \"apps\" in the namespace \"default\", failed to create default/redis-slave apps/v1, Kind=Deployment for  default/teststack: deployments.apps is forbidden: User \"system:serviceaccount:default:default-teststack-stack-629c5-dfbd1-stack\" cannot create resource \"deployments\" in API group \"apps\" in the namespace \"default\""
```

This other using `--permissions` flags too but it failed the RBAC role:

`rio up --name teststack2 --branch track_gvk --permission "* apps/deployments" --permission "* services" https://github.com/daxmc99/rio-demo`

```
is attempting to grant RBAC permissions not currently held:
{APIGroups:[""], Resources:["services"], Verbs:["*"]}
{APIGroups:["apps"], Resources:["deployments"], Verbs:["*"]}
```

Doing the exact same commands was working fine when I was testing Gitflow RBAC in alpha.4

**Comment by cbron** [comment]
Hmm, I just tried that riofile on k3s and it worked for me. If that works for you also then open a diff issue for that being GKE related permissions bug.

**Comment by izaac** [comment]
@cbron yeah, disregard, not sure why it wasn't working last night for me but it is working now in both GKE and k3s. I'll continue testing the export.

**Comment by izaac** [comment]
GVKs are getting now exposed using `rio export stack/<stack name>` I've tested with both local and github repo Riofiles.

Updating the Riofile with `rio up` and with proper permissions makes rio create the objects as k8s objects properly (where applicable). This is also stored in the stack and can be viewed now using `rio export` default to yaml and also json with the `--format json` flag.

Sample Riofiles used:
`rio up --name lts --permission "* apps/deployments" --permission "* services" -f ./Riofile`
`rio up --name ts --branch track_gvk --permission "* apps/deployments" --permission "* services" https://github.com/daxmc99/rio-demo`

Editing the Riofile and performing `rio up` to update the stack makes the proper changes both in rio and the objects in the k8s manifest in the stack and also `rio export` shows the stack changes.
