### ISSUE TITLE
Delete error message in CLI when config is not found

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rio#645]
The error message to detect whether rio is installed into the cluster is kind of buggy. We should remove it for now.

**Comment by davidnuzik** [comment]
Removed "big block" of content shown if config not found now. Should be fixed now.

**Comment by rancher-max** [comment]
The big block of content is gone in v0.6.0. It has been replaced by a FATAL error as described in the referenced issue above. We can enhance that in the future.
