### ISSUE TITLE
rio stage -e fails with  invalid character

### ISSUE THREAD

**Issue by lalyos** [rancher/rio#649]
**Describe the bug**

I run `rio stage -e `, and after making some trivial change in the yaml,
the editor opens up repeatedly with: "Error updating content: invalid character 'a' looking for beginning of value"

**To Reproduce**
1. rio run --name=nginx --env=ANSWER=41 -p 80 nginx
2. rio stage -e nginx
3. change 41 to 42 save/exit

**Expected behavior**

**Kubernetes version & type (GKE, on-prem)**: `kubectl version`
```
Client Version: v1.16.0
Server Version: v1.15.3
```
Type:
**Rio version**: `rio info`
```
Rio Version: v0.5.0 (303f3652)
Rio CLI Version: v0.5.0 (303f3652)
Cluster Domain: 4XXXXX4.on-rio.io
Cluster Domain IPs: 51.XXX.XX.118
System Namespace: rio-system

System Components:
activator status: running
autoscaler status: running
build-controller status: running
buildkitd-dev status: running
cert-manager status: running
controller status: running
gateway status: running
istio-pilot status: running
registry status: running
webhook status: running
```
**Additional context**
`rio systemlog`
output:
```
No help topic for 'systemlog'
```

**Comment by StrongMonkey** [comment]
@cbron Are you be able to test this on v0.6 see if it will be fixed?

**Comment by cbron** [comment]
Yes this was a bug in 0.5, it has been fixed on 0.6.

**Comment by lalyos** [comment]
I confirm, I just built the latest from master:
```
> rio --version
rio version v0.6.0-alpha.2 (d9675e43)
```
and its not an issue anymore.

**Comment by lalyos** [comment]
btw, thanks for the quick response
