### ISSUE TITLE
Add env option to stage command

### ISSUE THREAD

**Issue by cbron** [rancher/rio#650]
Add this to stage command: https://github.com/rancher/rio/blob/master/cli/cmd/create/create.go#L46
So that a user is able to add and update env variables via the CLI during a stage command. 

This issue is not critical, but a community user has requested it, so would be good to get in sooner.

**Comment by StrongMonkey** [comment]
Available to test in v0.6.0-alpha3.

**Comment by izaac** [comment]
I'm covering both `--env` and `--env-file` here in `rio v0.6.0-alpha.3` 

`--env` is working fine, both `rio export` and connecting to the pod shell show the envrionment variables being set. Same for `--env-file` but with env file it is also copying the comments to the right of the variable value like:

`VARIABLE=true # this is used for blah blah`

All to the right of the equal sign is getting set in the environment variable.

@StrongMonkey @cbron

**Comment by cbron** [comment]
Sounds like its working, closing.
