### ISSUE TITLE
Weight at 0% and no rollout on new versions when using --template and --version flags together

### ISSUE THREAD

**Issue by rancher-max** [rancher/rio#652]
**Describe the bug**
Running `rio run --template --version v1 https://github.com/rancher-max/rio-demo` ends up with a service that is at 0% weight. This is not an issue as it is the only service, but as soon as a new commit is pushed to the repository, then there become two services, both at 0% weight, and both with version of `test/v1`. Hitting the app or revision endpoints gives a mix of the two different codebases.

**To Reproduce**
1. `rio run --version v1 --template https://github.com/rancher/rio-demo`
^^ Use a GH repo that you have Write access to.
You can see the initial 0% weight issue with step 1.
2. Push a commit to the repo
Now executing `curl` on the endpoints gives a mix of both results.

**Expected behavior**
The initial version should be set to v1, and then new versions should rollout weight and be something different. I'm fine with it being the GH commit like `--template` flag usually works without the `--version` flag. Weight should also initially be 100% for v1.

**Kubernetes version & type (GKE, on-prem)**: `kubectl version` Using RKE - k8s 1.16
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
Type:
**Rio version**: `rio info`
```
Rio Version: v0.6.0-alpha.2 (d9675e43)
Rio CLI Version: v0.6.0-alpha.2 (d9675e43)
```
**Additional context**
`rio systemlogs`
output:
```
rio-controller | time="2019-10-31T16:44:03Z" level=info msg="Generating service default/spook-ccd1159-d7239 from template"
rio-controller | time="2019-10-31T16:44:32Z" level=info msg="Generating service default/confident-moore0-ccd1159-d7239 from template"
```

**More context on service statuses after two Git commits** 
```
gh-ccd1159-d7239                 default-gh-ccd1159-d7239:5e18e                 https://gh-v1-default.xxxxxx.on-rio.io:32269                     1         gh/v1                     0%        21 minutes ago   
gh-ccd1159-e9803                 default-gh-ccd1159-e9803:5dd41                 https://gh-v1-default.xxxxxx.on-rio.io:32269                     1         gh/v1                     0%        27 minutes ago   
gh-ccd1159-7af3d                 default-gh-ccd1159-7af3d:468d2                 https://gh-v1-default.xxxxxx.on-rio.io:32269                     1         gh/v1                     0%        29 minutes ago   
```

**Comment by cbron** [comment]
Fix will disallow template and version to be used together, and fix the weighting. Will be in next release.

**Comment by StrongMonkey** [comment]
Available to test in v0.6.0-alpha3. Not sure if this will actually fix it, but @rancher-max let us know if that doesn't work.

**Comment by rancher-max** [comment]
Well.. It looks like `--version` is no longer available to use with `rio run`. If this is the desired state, then yes it's fixed! I kind of like being able to set version value though.

**Comment by cbron** [comment]
Version was removed in latest refactor

**Comment by rancher-max** [comment]
So the new command to run this is: `rio run -n gtv@v1 --template https://github.com/rancher/rio-demo`

The 0% weight bug has been resolved, but the mix of results still happens. I believe #704 will address this.

**Comment by izaac** [comment]
We would need to revisit this after https://github.com/rancher/rio/issues/682 work is completed.

**Comment by StrongMonkey** [comment]
Available to test in alpha4. @izaac Make sure `rio run --template` work flow is fixed in alpha4.

**Comment by rancher-max** [comment]
Fixed in alpha4. Note that specifying service version does not do much with `--template` because whenever new commits are pushed, a unique version is picked automatically. 

`rio run --template` appears to be working correctly in alpha4
