### ISSUE TITLE
`rio weight` shouldn't change other svc weights

### ISSUE THREAD

**Issue by cbron** [rancher/rio#682]
Weight without percentage should change spec exactly. Example: If we have 2 services both at 50%, if I call `rio weight svc-b=20`, it should move only svc-b to 20, and not touch svc-a. 

Weight with percentage should change weight relative. Example: If we have 2 services both at 50%, if I call `rio weight svc-b=75%`, then the service should move to 150%. svc-a should not change. 

And fix tests

**Comment by cbron** [comment]
Available to test in v0.6.0-alpha3

**Comment by izaac** [comment]
This is working as described in this issue in the latest `rio v0.6.0-alpha.3`

**Comment by cbron** [comment]
Follow up changes: 

* Weights should be normalized in `rio ps`
* Interval should be normalized
* Interval/Increment should default to 0

**Comment by izaac** [comment]
For the scope of this issue this is passing in `rio v0.6.0-alpha.4`

**Comment by izaac** [comment]
Current behavior is as of `rio v0.6.0-alpha.4`:

> In the backend, the weight command still only edits a single version so it goes up and all others stay as-is. But when you do `rio ps` those should all equal 100%
> 
> The exception to that is when you set any version to 100% with either weight or promote, it will send that version to 100% and all others will get edited back to 0. Because its impossible to be 100% if another version has any weight.

Closing as we're meeting this requirement and this is how weights is behaving at the moment.
