### ISSUE TITLE
Add `rio pods` and `rio kill` commands

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rio#691]
`rio pods` show all the pods
`rio kill` kill all the pods(can be individual pods or pods from services)

**Comment by StrongMonkey** [comment]
Available to test in v0.6.0-alpha3. 
`rio kill` can take either pod name or service name, and will kill pods or pods that belongs to service.

**Comment by rancher-max** [comment]
Working in v0.6.0-alpha.3
