### ISSUE TITLE
Add incremental rollout validation test

### ISSUE THREAD

**Issue by cbron** [rancher/rio#698]
We pulled out the test from integration because it was flakey: https://github.com/rancher/rio/pull/695/files#diff-50cacc49c101777a487b479a60307c25R34

Getting errors around the object already being modified, since rollout modifies it consistently. We should add this back into validation testing.

**Comment by rancher-max** [comment]
This is already available in validation tests, but it needs to be fixed to address the cli's changed weight command

**Comment by davidnuzik** [comment]
If the effort is very, very low we can fix in v0.6.0 milestone if you wish; I'll leave that up to you.

**Comment by rancher-max** [comment]
#653 Closes this
