### ISSUE TITLE
Create a separate resource for staged service

### ISSUE THREAD

**Issue by sheng-liang** [rancher/rio#7]
Right now staged service always have the same create time as the original service:
```
sheng@ubuntu-sheng:~/Downloads$ rio ps
NAME                 IMAGE     CREATED         SCALE     STATE     ENDPOINT                                                    DETAIL
epic-bhaskara        nginx     4 minutes ago   1         active    http://epic-bhaskara.default.u2u8hs.lb.rancher.cloud        
epic-bhaskara:next   nginx     4 minutes ago   1         active    http://epic-bhaskara-next.default.u2u8hs.lb.rancher.cloud   
```
It's better to create a new resource and leave the existing service untouched.

**Comment by tfiduccia** [comment]
Version - v0.1.1-rc1
This is fixed.  You have to use "rio revision default/servicename" instead as the rio ps only shows the single service.
![image](https://user-images.githubusercontent.com/11514927/58206901-7ae0c400-7c96-11e9-8e85-8e33c9efa219.png)
