### ISSUE TITLE
unable to get custom domains working in rio v0.6.0-alpha.2

### ISSUE THREAD

**Issue by mbarlow** [rancher/rio#700]
**Describe the bug**
Using rio v0.6.0-alpha.2, trying to create a custom domain and unable to hit a deployed workload endpoint.

**To Reproduce**
1. after installing rio, create a new clusterdomain w/ contents (replace example.com and ip address with actual):

```
apiVersion: admin.rio.cattle.io/v1
kind: ClusterDomain
metadata:
  name: example.com
spec:                                                                                             
  addresses:                                                                                      
  - ip: 1.2.3.4                                                                              
  httpPort: 80                                                                                    
  httpsPort: 443                  
status:
  assignedSecretName: example.com-tls
  httpsSupported: true
```
2. create the secret example.com-tls for certs and set the crt, key using your custom domain cert
3. ```rio run -p 80/http --name riotest ibuildthecloud/demo:v1```
4. ```rio ps``` verify workload deployed and endpoint generated using your custom domain
5. Try to access endpoint and receive error messages.
6. Look at logs from gateway-v2 and see entries:
```
{"level":"info","ts":"2019-11-06T17:34:20.990Z","logger":"gateway.v1.event_loop.gateway.v2.event_loop.translatorSyncer.reporter","caller":"reporter/reporter.go:153","msg":"wrote report {riotest-ae2c81c6-tls-example.com-tls default} : {Accepted  gateway map[*v1.Proxy rio-system gateway-proxy-v2:state:Warning reason:\"warning: \\n  Route Warning: InvalidDestinationWarning. Reason: *v1.Upstream {kube-svc:default-riotest-ae2c81c6-80 default} not found\\nRoute Warning: InvalidDestinationWarning. Reason: *v1.Upstream {kube-svc:default-riotest-ae2c81c6-80 default} not found\\nRoute Warning: InvalidDestinationWarning. Reason: *v1.Upstream {kube-svc:default-riotest-ae2c81c6-80 default} not found\\nRoute Warning: InvalidDestinationWarning. Reason: *v1.Upstream {kube-svc:default-riotest-ae2c81c6-80 default} not found\\nRoute Warning: InvalidDestinationWarning. Reason: *v1.Upstream {kube-svc:default-riotest-ae2c81c6-80 default} not found\\nRoute Warning: InvalidDestinationWarning. Reason: *v1.Upstream {kube-svc:default-riotest-ae2c81c6-80 default} not found\" reported_by:\"gloo\" ] nil {} [] 0}"}
```
also see logs for gateway-proxy:
```
[2019-11-06 18:21:43.640][6][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:50] Unable to establish new stream
[2019-11-06 18:21:54.944][6][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:87] gRPC config stream closed: 14, no h
ealthy upstream
```

**Expected behavior**

Accessing workload when using a custom domain is successful

**Kubernetes version & type (GKE, on-prem)**: `kubectl version`
```
k8s: v1.16.2 on-prem
kubectl: v1.16.0
```
Type:
**Rio version**: `rio info`
```
Rio Version: v0.6.0-alpha.2 (d9675e43)
Rio CLI Version: v0.6.0-alpha.2 (d9675e43)
Cluster Domain: example.com
Cluster Domain IPs: 1.2.3.4
System Namespace: rio-system
Wildcard certificates: true

```
**Additional context**
`rio systemlogs`
output:
```
rio-controller | time="2019-11-06T00:29:48Z" level=info msg="Starting rio-controller, version: v0.6.0-alpha.2, git commit: d9675e43"
rio-controller | time="2019-11-06T00:29:48Z" level=info msg="Updating CRD services.rio.cattle.io"
rio-controller | time="2019-11-06T00:29:48Z" level=info msg="Updating CRD stacks.rio.cattle.io"
rio-controller | I1106 00:29:48.933978       1 leaderelection.go:241] attempting to acquire leader lease  rio-system/rio...
rio-controller | time="2019-11-06T00:29:48Z" level=info msg="listening at :443"
rio-controller | I1106 00:29:48.940156       1 leaderelection.go:251] successfully acquired lease rio-system/rio
rio-controller | time="2019-11-06T00:29:49Z" level=info msg="Starting /v1, Kind=ConfigMap controller"
rio-controller | time="2019-11-06T00:29:50Z" level=info msg="Starting apps/v1, Kind=DaemonSet controller"
rio-controller | time="2019-11-06T00:29:50Z" level=info msg="Starting admin.rio.cattle.io/v1, Kind=PublicDomain controller"
rio-controller | time="2019-11-06T00:29:50Z" level=info msg="Starting gloo.solo.io/v1, Kind=Settings controller"
rio-controller | time="2019-11-06T00:29:50Z" level=info msg="Starting rio.cattle.io/v1, Kind=ExternalService controller"
rio-controller | time="2019-11-06T00:29:50Z" level=info msg="Starting apps/v1, Kind=Deployment controller"
rio-controller | time="2019-11-06T00:29:50Z" level=info msg="Starting cert-manager.io/v1alpha2, Kind=Certificate controller"
rio-controller | time="2019-11-06T00:29:50Z" level=info msg="Starting extensions/v1beta1, Kind=Ingress controller"
rio-controller | time="2019-11-06T00:29:50Z" level=info msg="Starting /v1, Kind=Service controller"
rio-controller | time="2019-11-06T00:29:50Z" level=info msg="Starting /v1, Kind=Endpoints controller"
rio-controller | time="2019-11-06T00:29:50Z" level=info msg="Starting tekton.dev/v1alpha1, Kind=TaskRun controller"
rio-controller | time="2019-11-06T00:29:50Z" level=info msg="Starting admin.rio.cattle.io/v1, Kind=ClusterDomain controller"
rio-controller | time="2019-11-06T00:29:50Z" level=info msg="Starting /v1, Kind=Secret controller"
rio-controller | time="2019-11-06T00:29:50Z" level=info msg="Starting rio.cattle.io/v1, Kind=Service controller"
rio-controller | time="2019-11-06T00:29:50Z" level=info msg="Starting rbac.authorization.k8s.io/v1, Kind=ClusterRoleBinding controller"
rio-controller | time="2019-11-06T00:29:50Z" level=info msg="Starting apps/v1, Kind=StatefulSet controller"
rio-controller | time="2019-11-06T00:29:50Z" level=info msg="Starting rio.cattle.io/v1, Kind=Router controller"
rio-controller | time="2019-11-06T00:29:50Z" level=info msg="Starting rbac.authorization.k8s.io/v1, Kind=ClusterRole controller"
rio-controller | time="2019-11-06T00:29:50Z" level=info msg="Starting rio.cattle.io/v1, Kind=Stack controller"
rio-controller | time="2019-11-06T00:29:50Z" level=info msg="Starting gitwatcher.cattle.io/v1, Kind=GitCommit controller"

```

**Comment by daniel-sullivan** [comment]
@StrongMonkey Any ideas what might be causing this one? Currently have some time to set up a new deployment based around 0.6.0 and need to fix this before I can get it going (we use an internal CA and would like to set it up the same as how we had with the current 0.4.0 deployment with the clusterDomain being the same as the wildcard). I'm going to dig into the code a bit this morning but any direction would be great

**Comment by StrongMonkey** [comment]
@daniel-sullivan  Can you try the steps defined in here and let me know if that works? https://github.com/rancher/rio/blob/master/docs/faq.md  Also @mbarlow Not sure if i recalled it correctly, did you eventually get it working in a local cluster?

**Comment by daniel-sullivan** [comment]
@StrongMonkey I just found that new commit about 45 seconds before you replied! Whatever they're paying you it's not enough - that method works perfectly!

For the record, the method I was using previously was the same as in the FAQ except for:

Install with ```rio install --disable-features letsencrypt --disable-features rdns --disable-features build --enable-debug```

This method would not create a clusterDomain automatically and I would then apply a ClusterDomain as mbarlow was doing, along with the TLS wildcard record

This resulted in:
```
charm@kame1:~$ rio info
Rio Version: v0.6.0 (c1bff129)
Rio CLI Version: v0.6.0 (c1bff129)
Cluster Domain: production.ourcompany.internal
Cluster Domain IPs:
System Namespace: rio-system
Wildcard certificates: false
```
Along with:
```
rio ps
NAME         IMAGE                    ENDPOINT                                                 PORTS     SCALE     WEIGHT    CREATED        DETAIL
riotest      ibuildthecloud/demo:v1   http://riotest-v0-default.production.ourcompany.internal      80        1         100%      17 hours ago
```

This endpoint was successfully accessible via http however https would give a "Connection Terminated" error in the browser, and a "Connection Refused to :8443" message in linkerd-proxy

So, the question is, does this mean moving forward we need to install letsencrypt / rdns and also keep the additional *****.on.rio clusterDomain around to have the https layer come up correctly when using a custom clusterDomain?

**Comment by StrongMonkey** [comment]
It doesn’t require you to have rdns and lets encrypt, something is probably configured wrong on the tls side. I can take a look at it later, not in a computer right now.

**Comment by daniel-sullivan** [comment]
All good, there's no rush. Got more than enough to be getting on with now. Interestingly, after following your steps, THEN re-running rio install with the flags I had above, followed by deleting the ***.on.rio clusterDomain record using kubectl, we get the same rio info as before but newly created instances have working https under the custom clusterDomain

```
Rio Version: v0.6.0 (c1bff129)
Rio CLI Version: v0.6.0 (c1bff129)
Cluster Domain: production.ourcompany.internal
Cluster Domain IPs:
System Namespace: rio-system
Wildcard certificates: false
```

**Comment by rancher-max** [comment]
it looks like this is working now in v0.6.0 when following the steps mentioned in the docs. I'd say there are still a few issues with it though that we should iron out:
1. I would want `rio info` to show ALL of the cluster domain's I have applied in a comma separated list, similar to how it does for IPs.
2. `rio info` should show `Wildcard certificates: true` as mentioned above.
3. The endpoints only show http even though https is available. 

Also this seems like it would be a nice-to-have feature on install. Something like: `rio install --cluster-domain my.production.domain --cert /path/to/cert --key /path/to/key`

I'll create enhancement issues for all of these as this looks like it's closed to me now. Feel free to reopen if you still notice problems!

**Comment by mbarlow** [comment]
I am still seeing the same problems using v0.7.0.

Steps followed:

1. rio install --disable-features letsencrypt --disable-features rdns
2. create the wildcard tls secret as specified in the docs link above (my.domain.com-tls in rio-system namespace)
3. create the clusterdomain (my.domain.com) as specified in link above 
4. run rio info, see clusterdomain listed correctly, wildcard for my.domain.com-tls is (false)?
5. rio run -p 80:8080 https://github.com/rancher/rio-demo
6. rio ps shows only http endpoint for demo
7. rio inspect only shows http for demo
