### ISSUE TITLE
Port must be set on service creation to get an endpoint from rio

### ISSUE THREAD

**Issue by izaac** [rancher/rio#706]
**Describe the bug**
If we don't specify a port now rio won't set an endpoint for the service.
We need to document this because this a functionality change in `rio v0.6.0-alpha.3`

**To Reproduce**
1. `rio run -n ascaler strongmonkey1992/autoscale:testing`
2. `rio ps` after the pods are initialized there won't be an endpoint created for the service (ascaler)

** Expected behavior **

Use `--ports`/`-p` on rio run to get an endpoint.

**Comment by cbron** [comment]
Definitely need to document it. I also threw out this as a alternative solution: https://github.com/rancher/rio/pull/702

**Comment by cbron** [comment]
Should be able to close this one, the 0.6.0 docs have port in all examples and 702 was merged.
