### ISSUE TITLE
Use of wrong flags makes rio to get stuck without failing

### ISSUE THREAD

**Issue by izaac** [rancher/rio#707]
**Describe the bug**
rio is stuck if I use a wrong flag during `rio run` for example.

**To Reproduce**
1. install rio
2. do a `rio run --helop` wrongly setting the flag with a typo
3. rio is stuck there without failing

Shell I'm using is `zsh 5.7.1 (x86_64-apple-darwin19.0)` Mac OS Catalina 10.15.1

**Expected behavior**

Make rio fail quick if there are wrong flags set during CLI invocation.

**Kubernetes version & type (GKE, on-prem)**: `kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2-k3s.1", GitCommit:"b8b17ba55f20e590df507fce333dfee13ab438c6", GitTreeState:"clean", BuildDate:"2019-10-16T05:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
Type:
**Rio version**: `rio info`
```
rio version v0.6.0-alpha.3 (98e09134)
```
**Additional context**
`rio systemlogs`
output:
```
Nothing relevant in systemlogs
```

**Comment by jgillich** [comment]
Big oof. Ran into this well, tried to do `rio install --no-deploy traefik` (which is actually a k3s option).

**Comment by rancher-max** [comment]
Working now in master (0.6.x).

Now the behavior is that it will give the default `--help` result, followed by a FATAL error, such as: `FATA[0000] flag provided but not defined: -helop`
