### ISSUE TITLE
Rio should throw a warning/error when doing rio logs on a service that has scale zero [v0.6.0-alpha.3]

### ISSUE THREAD

**Issue by izaac** [rancher/rio#708]
**Describe the bug**
When a service has SCALE zero, if we try to see the logs using `rio logs <service>` rio just sits there doing nothing. 

`rio exec <service> <command>` throws an error.

```bash
rio exec ascaler uname
FATA[0000] failed to find any pod for service ascaler, container ""
```

**To Reproduce**
1. create a service with auto scaling from 0 to X.
2. `rio ps` the service and check the scale is 0
3. `rio logs <service>`

rio logs just sits there without doing anything, I had to CTRL-C.

**Expected behavior**

Throw an error when using `rio logs` and scale is zero like with `rio exec` 

**Kubernetes version & type (GKE, on-prem)**: `kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-eks-5047ed", GitCommit:"5047edce664593832e9b889e447ac75ab104f527", GitTreeState:"clean", BuildDate:"2019-08-21T22:32:40Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
Type:
**Rio version**: `rio info`
```
Rio Version: v0.6.0-alpha.3 (98e09134)
Rio CLI Version: v0.6.0-alpha.3 (98e09134)
Cluster Domain: xxxxx.on-rio.io
Cluster Domain IPs:
System Namespace: rio-system
Wildcard certificates: true
```
**Additional context**
`rio systemlogs`
output:
```
Nothing unusual on systemlogs.
```

**Comment by rancher-max** [comment]
This now shows `Waiting for pods...` and then shows logs. However, it has the same issue as https://github.com/rancher/rio/issues/772#issuecomment-558804763 where it does not have log results:
```
Waiting for pods...
                                               
+ default gh-v0wrtkd-659f4c9fc4-fj566 › gh-v0wrtkd
Error opening stream to default/gh-v0wrtkd-659f4c9fc4-fj566: gh-v0wrtkd
: container "gh-v0wrtkd" in pod "gh-v0wrtkd-659f4c9fc4-fj566" is waiting to start: PodInitializing
```
That is all that ever shows up, even after curling the endpoint, where I should see logs.

**Comment by rancher-max** [comment]
This now shows `Waiting for pods...` until a pod starts up from the service being accessed, then works properly, showing log output from the service.
