### ISSUE TITLE
`rio endpoint` doesn't show publicdoman as https

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rio#713]
Steps to reproduce:

1. Register a domain. `rio domain register`
2. `rio endpoints`
3. Publicdomain endpoints are not showed as `https`

**Comment by StrongMonkey** [comment]
available to test in v0.6.0-alpha5.

**Comment by rancher-max** [comment]
On GKE this gave the http edpoint after `rio endpoint` but on k3s it gave https endpoint. I believe @StrongMonkey has a fix incoming for this.

**Comment by rancher-max** [comment]
Appears to be fixed in the cluster that was showing http endpoint previously with rio version v0.6.0-rc1
