### ISSUE TITLE
Verify weight calculations and add unit tests 

### ISSUE THREAD

**Issue by daxmc99** [rancher/rio#719]
The weight calculation in the rollout controller and weight/promote CLI needs to more formally verified to address possible edge cases. 

- [x] duration may need to scale dynamically up and down instead of being stuck at 2 seconds
- [x] (from comments) look into making rollout more gradual, especially with larger durations
- [x] math can be broken out and unit tested
- [x] check for rounding (floor/ceiling) issues, especially around weight setting

**Comment by daxmc99** [comment]
Also need to test for high conflict levels during rollout per @izaac

**Comment by rancher-max** [comment]
Just something to review as part of this:
`rio weight --duration=1m test@v2=60` Seems like it should rollout 1% per second, but does 20% in the first 10 seconds, is pretty gradual in the middle, then takes around 25 seconds for the final 10%.
This is somewhat expected as part of the "only-touch-one-service" system, but I think should just be double checked into our options here.

**Comment by izaac** [comment]
> Just something to review as part of this:
> `rio weight --duration=1m test@v2=60` Seems like it should rollout 1% per second, but does 20% in the first 10 seconds, is pretty gradual in the middle, then takes around 25 seconds for the final 10%.
> This is somewhat expected as part of the "only-touch-one-service" system, but I think should just be double checked into our options here.

This is even more noticeable when using hours.

**Comment by rancher-max** [comment]
Weight is all an approximation, but this is working much much better now in master. It is pretty gradual now.

I would recommend users who want to slowly rollout weight, but overall aren't worried about their new version stability, to use the gradual duration feature.
I would recommend users who are more cautious and want greater rigidity to specify a small weight amount for their new versions (either roll it out gradually or immediately) and monitor traffic accordingly. If pleased, increase that weight a little bit and continue until full promote is desired.
