### ISSUE TITLE
rio up gitrepo needs a way to differentiate the environment

### ISSUE THREAD

**Issue by lucidprogrammer** [rancher/rio#730]
Enhancement request:

currently one can do the following
`
rio -n jc up --name test --branch master --build-clone-secret gitcredential --build-webhook-secret githubtoken https://github.com/riotesting/rio-demo
`
There should be a way to specify the riofile corresponding to the stack. Currently, there is no way to dynamically determine the context. So ideally some way to specify the riofile/answers or some way to do {{- if eq .metadata.namespace "jc" }}

**Comment by rancher-max** [comment]
This appears to be working in v0.6.0. You fixed your own bug, thank you!

In case anyone else has this issue, by default now the `NAMESPACE` question is available, so you can use `{{- if eq .Values.NAMESPACE "jc" }}` in your Riofile by just setting:
```
...
template:
  goTemplate: true
```

Refer to [riofile docs](https://github.com/rancher/rio/blob/master/docs/riofile.md) for more info.
