### ISSUE TITLE
rio up on repo without a Riofile builds everything to the same service name

### ISSUE THREAD

**Issue by rancher-max** [rancher/rio#733]
**Describe the bug**
When running `rio up <repo url>` with a Github repository that does not have a Riofile, the service name is always `source@{hash}`. This is fine when only doing it for one repo, but trying with multiple repos causes overwrites of the service. 
See: https://github.com/rancher/rio/issues/627#issuecomment-550412802

**To Reproduce**
1. `rio up --name diffname1 https://github.com/rancher-max/rio-demo`
2. `rio up --name diffname2 https://github.com/rancher/rio-demo` (different repo)
3. `rio ps` only shows one service, named `source@{hash}` and it will point to the second repo.

**Expected behavior**
I'd like the service names to be the name I specify in this case, or at least 2 different names so that both applications are available.

Type:
**Rio version**: `rio version v0.6.0-alpha.4 (969baf29)`

**Comment by davidnuzik** [comment]
Closing in favor of #744 (nearly same exact thing).
