### ISSUE TITLE
Traffic split inside cluster doesn't work

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rio#738]
Step to reproduce:

1. create two service a and b, give them 50 and 50 weight.
2. Create another service, and access app endpoint to the service a and b inside this service.
3. no traffic split.

**Comment by StrongMonkey** [comment]
fixed https://github.com/rancher/rio/issues/738

**Comment by cbron** [comment]
@StrongMonkey bad link

**Comment by StrongMonkey** [comment]
available to test in v0.6.0-alpha5.

**Comment by rancher-max** [comment]
Working in v0.6.0-alpha.5. Steps:

1. `rio run -n demo ibuildthecloud/demo:v1`
2. `rio stage --image ibuildthecloud/demo:v2 v2`
3. `rio weight demo@v2=50`
4. `rio stage --image ibuildthecloud/demo:v3 v3`
5. `rio endpoint`
6. `curl` endpoint a few times --> successful mix of v2 and v1
7. `rio exec -it demo /bin/sh`
In the resulting shell....
1. `apt-get update`
2. `apt-get install curl`
3. `curl demo` a few times --> successful mix of v2 and v1
