### ISSUE TITLE
Clean labels during stage cmd, and tweak weight cmd. 

### ISSUE THREAD

**Issue by cbron** [rancher/rio#745]
This issue is to handle a few miscellaneous things that came up during QA/testing. 

1. When staging a rio service, annotations and labels that contain `*.cattle.io/*` should be removed. 
2. The "promoted" message should not be printed for weight=100 commands
3. Duration for a rollout should be limited to 24 hours.

**Comment by izaac** [comment]
Number 1:

I was able to set Metadata Labels and Annotations and check if they are being preserved if they don't match the `rio.cattle.io` string. 

By doing `rio up -n tsmax https://github.com/rancher-max/riofile-demo` inspecting the services to validate the annotations/labels were there and then staging one of the services created.

After further inspection of the staged service I no longer get the ones matching `rio.cattle.io`.

Number 2: **Fixed**

Number 3:

Rollout duration limit is 10 hours not 24 as implemented in v0.6.0-RC1. Also if the difference between current weight and target weight are slim  and the duration is below 10 hours this is displaying:

`Unable to perform rollout, given duration too long for current weight` Which is expected.

Trying to go above 10 hours (10h, 36001s):

`cannot perform rollout longer than 10 hours`

I've opened a separate issue for an scenario I ran with weight issues. https://github.com/rancher/rio/issues/769
