### ISSUE TITLE
Can't run rio services with persistent volume enabled

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rio#767]
Steps to reproduce:

1. `rio run -v foo:/data,persistent=true nginx`

Service returns error: silly-moore-mf4fs: not ready; ServiceDeployed: failed to find informer for /v1, Kind=PersistentVolumeClaim for service default/silly-moore-mf4fs(Error)

**Comment by izaac** [comment]
I've tested this in `k3s v0.10.2` using `rio v0.6.0-rc2`

Rio created the service properly. The volume was configured in the service and the mount can be checked in the container mounted as expected.
Scaling the service with rio. I can see the volume shared with other containers in the service too.

Tested also in GKE with `k8s v1.15.4-gke.18` using `rio v0.6.0-rc2`.
