### ISSUE TITLE
Weight can't be changed from 100 when using rio ps after rolling to/from 100%

### ISSUE THREAD

**Issue by izaac** [rancher/rio#769]
**Describe the bug**
This one is very tricky, but is a combination of using `--duration` and then manually setting the weight of a staged service. After certain points (check the steps, I can't make rio show the actual weight with `rio ps` it just always show 100%.

**To Reproduce**
1. Create a service
2. Create a stage version of the service from step 1
3.`rio weight service@version=99` (rio ps shows weight 99)
4.`rio weight --duration 1s service@version=100` (rio ps shows weight 100)
5. `rio weight --duration 1s service@version=99` (rio ps shows weight 100)
6. `rio inspect service@version` shows weight: 99
7. `rio weight  service@version=100` `FATA[0000] cannot rollout, already at target percentage`
8. `rio weight  service@version=50` (rio ps shows weight 100)
9. `rio weight  service@version=50` (rio ps shows weight 100)
10. `rio inspect service@version` shows weight: 99

**Expected behavior**

Being able to set the weight im telling to rio after rolling up and down the service.

**Kubernetes version & type (GKE, on-prem)**: `kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2-k3s.1", GitCommit:"b8b17ba55f20e590df507fce333dfee13ab438c6", GitTreeState:"clean", BuildDate:"2019-10-16T05:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
Type:
**Rio version**: `rio info`
```
Rio Version: v0.6.0-rc1 (1dec45ce)
Rio CLI Version: v0.6.0-rc1 (1dec45ce)
Cluster Domain: xxxxxx.on-rio.io
Cluster Domain IPs: x.x.x.x
System Namespace: rio-system
Wildcard certificates: true
```
**Additional context**
`rio systemlogs`
output:
```

```

**Comment by cbron** [comment]
This is desired behavior, the weight seen in `rio ps` is always the normalized weight. So if you have 100/100 that resolves to 50%/50%. In this case you set 99/0 which would still resolve to 100%/0.
