### ISSUE TITLE
Test cosmetic and vendor changes

### ISSUE THREAD

**Issue by cbron** [rancher/rio#792]
https://github.com/rancher/rio/pull/790 - run through new flags, and `rio -s ps` should show `v0` on all system services instead of random numbers. 

https://github.com/rancher/rio/pull/791 - see comment, ensure that riofile doesn't panic now. It won't work but thats ok, its not supposed to.

**Comment by rancher-max** [comment]
It doesn't show v0 since I think we hide that by default, but it does look much nicer, and the endpoints have v0 now instead of the random numbers. 

The riofile from #532 did not have a panic anymore. The new output:
```
default:stack/rio
FATA[0004] json: cannot unmarshal string into Go struct field ExternalRiofile.configs of type v1.ConfigMap 
```
