### ISSUE TITLE
rio install --disable-features gloo waits forever for gloo component installation

### ISSUE THREAD

**Issue by izaac** [rancher/rio#800]
**Describe the bug**
`rio install --disable-features gloo` proceeds with the installation but keeps waiting for gloo to be ready.

**To Reproduce**
1. `rio install --disable-features gloo`  

**Expected behavior**

Gloo not installed ? Should we allow this feature to be disabled at all?

**Kubernetes version & type (GKE, on-prem)**: `kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2-k3s.1", GitCommit:"b8b17ba55f20e590df507fce333dfee13ab438c6", GitTreeState:"clean", BuildDate:"2019-10-16T05:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
Type:
**Rio version**: `rio info`
```
rio v0.6.0-rc2
```

**Comment by davidnuzik** [comment]
in rc3

**Comment by izaac** [comment]
Validated this use case in `rio v0.6.0-rc3` Other features use cases, disabling:

linkerd
build
dashboard
autoscaling
letsencrypt
rdns

also worked.
