### ISSUE TITLE
Buildkitd failed to start

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rio#826]
Buildkitd will stuck if there is no default storage class in k8s cluster. This is because there is a mapper bug that failed to disable the persistent volume option for builkitd.

Step to verify:
1. Create k3s cluster, edit `storageCLass` label to make local storage not default

`storageclass.kubernetes.io/is-default-class: "false"`

2. RIo install

It will stuck at rio-system/buildkitd

Expected behavior:
If there is default storageClass, buildkitd(registry) will use pvc for /var/lib/registry, which means all image data are persisted. 
If there is no default storageClass, emptyDir will be used for `/var/lib/registry,`

**Comment by rancher-max** [comment]
Working on both k3s and RKE (which by default does not have any storageclass). 

Also, now when a cluster does have a storageclass, if the buildkitd pod is terminated, the  built images are persisted.
