### ISSUE TITLE
rio --system-namespace makes rio get stuck waiting for components in rio-system to be ready.

### ISSUE THREAD

**Issue by izaac** [rancher/rio#829]
**Describe the bug**

Telling rio to install in a different system namespace makes rio wait for system services in `rio-system`

**To Reproduce**
1. `rio --system-namespace ns install`
2. Rio stuck

```bash
Deploying Rio control plane....
\ Waiting for system components: [rio-system/autoscaler rio-system/buildkitd rio-system/cert-manager ...]
```

**Expected behavior**

Make rio wait for these components in the custom system namespace specified during installation.

Type:
**Rio version**: `rio info`
```
rio v0.6.0-rc3
```

**Comment by izaac** [comment]
This is a regression introduced in the fix of this issue: https://github.com/rancher/rio/issues/800

**Comment by StrongMonkey** [comment]
@izaac Probably not a regression. It doesn't work because the deployment and namespace are always hard-coded.

**Comment by izaac** [comment]
@StrongMonkey yes you're right this is a dupe: https://github.com/rancher/rio/issues/765
