### ISSUE TITLE
Rio user will block rancher user login

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rio#841]
If you are using rancher to provision and manage k8s cluster, and install Rio on it, the rio user and rancher user will be duplicated and clash. 
To fix simply rename the rio admin user: 
* `kubectl patch users.management.cattle.io admin --type='json' --patch='[{"op": "replace", "path": "/username", "value":"rio-admin"}]'`
* use the rancher admin user to login to rancher and rio dashboard

**Comment by StrongMonkey** [comment]
The bug is because we create duplicated username in rio that conflicts with rancher user. 

Workaround:
`kubectl patch users.management.cattle.io admin --patch '{"username": "rio-admin"}'`

**Comment by StrongMonkey** [comment]
@rancher-max should be fixed in master now.

**Comment by rancher-max** [comment]
Dashboard is broken and inaccessible in master

**Comment by rancher-max** [comment]
I believe this has been fixed in v0.7.0.

I could access the dashboard in both on rke cluster and gke. My steps:
1. `rio install`
2. `rio run -p 80:8080 https://github.com/rancher/rio-demo`
3. Wait for https endpoint to be available, then access it
4. `rio dashboard`
