### ISSUE TITLE
Endpoints for custom cluster domains only show http even if https is available

### ISSUE THREAD

**Issue by rancher-max** [rancher/rio#850]
Both the http and https endpoints should be available when using custom cluster domains and specifying both. It should default to showing https in the cli.

Current state does not show the https endpoint at all, and it's not in the manifest when using `rio inspect` to get endpoints.

Reference: rancher/rio#700

**Comment by rancher-max** [comment]
https is shown when it is specified and a secret is supplied. When a secret is not supplied, https is not supported and then only http is shown.

**Comment by mbarlow** [comment]
@rancher-max can you give more details for: https is shown when it is specified and a secret is supplied? How is https specified and how is secret supplied? I followed the instructions here:  https://github.com/rancher/rio/blob/master/docs/faq.md at bottom creating a clusterdomain with the entry secretName set to my wildcard tls secret and `rio info` still shows (false) for my wildcard and deploying a workload w/ rio still only shows http for endpoint when doing `rio ps` or `rio inspect`. I am using v0.7.0.

**Comment by rancher-max** [comment]
@mbarlow We did some investigating on this. Following the steps from here: https://github.com/rancher/rio/issues/700#issuecomment-572414602 if you just do a bare `rio install` OR `rio install --disable-features rdns` it should work. I'm noticing that for some reason it does not work when we disable letsencrypt as it appears to only set ClusterDomain to https inside the LE controller. 

Will use https://github.com/rancher/rio/issues/990 to enhance this functionality.
