### ISSUE TITLE
Cannot delete rio-system namespace

### ISSUE THREAD

**Issue by iMerica** [rancher/rio#855]
**Describe the bug**
I deleted the rio-system namespace hours ago and it's still stuck in "Terminating".

**To Reproduce**
1. Delete the rio namespace (in an effort to delete all rio things from my cluster).

**Expected behavior**
I expect the name space to be removed in a timely manner. 

**Kubernetes version & type (GKE, on-prem)**: `kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:11:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
Type:
**Rio version**: `rio info`
```
Rio Version: v0.6.0 (c1bff129)
Rio CLI Version: v0.6.0 (c1bff129)
Cluster Domain: owklow.on-rio.io
Cluster Domain IPs: 134.209.142.223
System Namespace: rio-system
Wildcard certificates: true
```

**Comment by iMerica** [comment]
Do you guys have a URL I can use to do `k delete -f <url>`and try to purge all rio things from my cluster?

I'm trying to start all over because the rio has not been working properly.

**Comment by daniel-sullivan** [comment]
I've had a similar issue with an earlier version. Try using this command:
```
kubectl -n rio-system api-resources --namespaced=true -o name | xargs --verbose -I {} kubectl -n rio-system get {} --show-kind --ignore-not-found
```

This will get ALL of the resources that are still holed up in the NS preventing the termination. Then you can go through and run one by one eg:

```
kubectl delete service.rio.cattle.io/gateway -n rio-system
```

**Comment by cbron** [comment]
Yes thats a known issue: https://github.com/rancher/rio/issues/724 so I'm going to close this as duplicate.

Removing a stuck namespace can be done with this: https://github.com/rancher/rio/issues/724#issuecomment-555773526

Cancelling the rio command and retrying might help. 

There's also this option to try to do a more manual uninstall of resources if you used default install params:
```
rio install --yaml | kubectl delete -f -
linkerd install --ignore-cluster | kubectl delete -f - 
```

**Comment by iMerica** [comment]
This was taking hours to delete. I had to destroy the entire cluster to move forward.
