### ISSUE TITLE
Install full rio -Error creating: Timeout: request did not complete within requested timeout

### ISSUE THREAD

**Issue by Pomazan-Bogdan** [rancher/rio#890]
**Describe the bug**
Dont create pod in install rio 
![image](https://user-images.githubusercontent.com/696713/70163213-c48b7c00-16c7-11ea-9d07-a3c91b9f77fb.png)

**To Reproduce**
1.  rio install

**Expected behavior**
Error in all not create pods:
```
Deploying Rio control plane....
/ Waiting for system components: [rio-system/autoscaler rio-system/cert-manager rio-system/gateway-proxy-v2 ...]
```

**Kubernetes version & type (GKE, on-prem)**: `kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3-k3s.2", GitCommit:"e7e6a3c4e9a7d80b87793612730d10a863a25980", GitTreeState:"clean", BuildDate:"2019-11-18T18:31:23Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

v1.16.3-k3s.2   
CentOS Linux 7 (Core)  
 3.10.0-1062.4.3.el7.x86_64   
containerd://1.3.0-k3s.4
```
Type:
**Rio version**: `rio info`
```
Rio Version: v0.6.0 (c1bff129)
Rio CLI Version: v0.6.0 (c1bff129)
Cluster Domain: qdpftv.on-rio.io
Cluster Domain IPs: 80.211.195.192
System Namespace: rio-system
Wildcard certificates: false
```
**Additional context**
all node 1cpu/2Gb

I started it 3 times in a row, and each time I made a new cluster.

**Comment by Pomazan-Bogdan** [comment]
Now install
But:
`Error cleaning up challenge: expect 200, got 500. Error: {"status":500,"msg":"failed to filter TXT records: _acme-challenge.fepzfp.on-rio.io","data":{},"token":""}`

**Comment by Pomazan-Bogdan** [comment]
Job has reached the specified backoff limit
linkerd-install-c4pz7-bk5ng

**Comment by Pomazan-Bogdan** [comment]
```
2019-12-04T18:04:28.953405557-05:00 podsecuritypolicy.policy/linkerd-linkerd-control-plane
2019-12-04T18:04:28.953409882-05:00 
2019-12-04T18:04:28.953414245-05:00 If you are sure you'd like to have a fresh install, remove these resources with:
2019-12-04T18:04:28.953418442-05:00 
2019-12-04T18:04:28.953422957-05:00     linkerd install --ignore-cluster | kubectl delete -f -
2019-12-04T18:04:28.953427245-05:00 
2019-12-04T18:04:28.95343167-05:00 Otherwise, you can use the --ignore-cluster flag to overwrite the existing global resources.
2019-12-04T18:04:28.954344183-05:00 error: no objects passed to apply
```

**Comment by StrongMonkey** [comment]
@Pomazan-Bogdan Have you got a chance to take look at k3s logs to see why pod failed to come up?

**Comment by Pomazan-Bogdan** [comment]
> Job has reached the specified backoff limit
> linkerd-install-c4pz7-bk5ng

Now this step good work, and return firs error https://github.com/rancher/rio/issues/890#issue-532815310

**Comment by Pomazan-Bogdan** [comment]
```
Created <1m ago (2019-12-05T14:01:53Z)
Name autoscaler-8c5658699.15dd7e7b7ef6cb39
Namespace rio-system
Link /api/v1/namespaces/rio-system/events/autoscaler-8c5658699.15dd7e7b7ef6cb39
Message Error creating: Timeout: request did not complete within requested timeout
Reason FailedCreate
Source replicaset-controller
```

**Comment by rancher-max** [comment]
@Pomazan-Bogdan I tried a few different configuration options and saw some of the same behavior. (**TLDR: Suggestion: try setting up your cluster with a master node of 2CPU, 4GB. Potentially can use this as the only node in your k3s cluster if trying to keep costs down**) I'm not sure how many nodes you had in your cluster or the full config of it, but below are my guesses of what you did and attempts to recreate. I'm taking into account the issue from here https://github.com/rancher/dashboard/issues/192 as well:

_All of these used the following:_
```
 Kernel Version:             3.10.0-957.27.2.el7.x86_64
 OS Image:                   CentOS Linux 7 (Core)
 Operating System:           linux
 Architecture:               amd64
 Container Runtime Version:  containerd://1.3.0-k3s.4
 Kubelet Version:            v1.16.3-k3s.2
 Kube-Proxy Version:         v1.16.3-k3s.2
```
_Configurations_:
- 2 Nodes: 1 CPU, 2GB each --> System pods all came up, but running `rio dashboard` took a very long time for it to load. After it finally did, I tried creating a service the same way you did (clicking "Start" on the first box from the home screen) and it failed with the 504 error. I then tried to run a service through the CLI and it also failed with a Timeout error.
- 2 Nodes: 1 CPU, 3GB each --> Exact same result as above
- 2 Nodes: 2 CPU, 2GB each --> Exact same result as above
- **1 Node: 2 CPU, 4GB --> Ran the same steps, successfully created! I'm suspecting that _at least_ the master node in your cluster needs to have this configuration for everything to work properly.**

**Comment by Pomazan-Bogdan** [comment]
I resetup cluster in RKE end RIO install good.

 ![image](https://user-images.githubusercontent.com/696713/70273100-1c061680-17b2-11ea-90e5-d5e18db9094f.png)

**Comment by Pomazan-Bogdan** [comment]
I add 1 vpn 4cpu/8GB and resetup k3s.
rio good install

But the fact that he does not stand on the cluster k3s (3 node  * 1cpu/2Gb), but to stand on the same iron on the RKE cluster is a fact.
I put it 2 times on the RKE+prometeus (lens-metrics/512m) and twice successfully (although yes, the place was 1.5 GB out of 6.

**Comment by rancher-max** [comment]
One more part of the problem can be installing k3s on CentOS. I tried the same setups using Ubuntu and they actually all worked successfully for me. 

From the official docs page of k3s, https://rancher.com/docs/k3s/latest/en/installation/node-requirements/ it was officially verified on Ubuntu and there is no mention of CentOS. I know it _should_ work, but likely that is the problem.

Thank you for bringing this to our attention though. Hopefully this will help others who have the same issues!
