### ISSUE TITLE
Building image with local context from Riofile gives sha256 tag instead of revision tag

### ISSUE THREAD

**Issue by rancher-max** [rancher/rio#897]
**Describe the bug**
Using Riofile to build image with local context (from github repo) and giving a custom image name uses a sha256 hash as the tag instead of revision

**To Reproduce**
1. Create a Riofile that builds from a local context. I have one here for use: https://github.com/rancher-max/riofile-demo/tree/image-rev
2. Run `rio up --branch image-rev https://github.com/rancher-max/riofile-demo`
3. After everything builds (`watch rio build-history`) run `rio ps` to see the image tags:
```
NAME                 IMAGE                                                                                            ENDPOINT                                              PORTS     SCALE     WEIGHT    CREATED              DETAIL
custrev@46942e6d     myname/custimage:6dccf                                                                           https://custrev-46942e6d-default.xc4csx.on-rio.io     8080      1         100%      About a minute ago   
custlocal@393910f8   localcontext/blahimage@sha256:074349ee875768e74fa17ab930d85af1f15869145cf750fc16fd8ccccf76dc08   https://custlocal-393910f8-default.xc4csx.on-rio.io   8080      1         100%      About a minute ago   
```

`custrev` is good, but `custlocal` is not.

**Expected behavior**
I would expect the image for `custlocal` to be: `localcontext/blahimage:aa0a6`

**Comment by StrongMonkey** [comment]
There is a reason to do that, we only change image tag when sha256 is changed, not when new commit is pushed. So if you just change other files not related to source code, image tag will not be changed.
