### ISSUE TITLE
Istio service mesh and own ingress controller

### ISSUE THREAD

**Issue by git001** [rancher/rio#900]
rio looks quite interesting therefore I have several questions about customization.

* How can I use istio service mesh?
* How can I use my another ingress controller like HAProxy one?

**Comment by StrongMonkey** [comment]
Hope this answer helps.

a)  Rio doesn't ship istio by default at this moment, but it can be configured to use istio service mesh outside out of Rio. Under the hood Rio programs (SMI)[https://smi-spec.io/] so istio can be supported.
We don't do testing around istio but if you want to take a try make sure you disable linkerd feature first. Check [here](https://github.com/rancher/rio/blob/master/docs/install.md#features) to see how to disable feature.
b) We are going to add support for ingress in the next release. Right now all ingress traffic are served by (gloo)[https://github.com/solo-io/gloo], but you will be able to swap it out with your own ingress controller in the next release.

**Comment by wmorgan** [comment]
Is there something you're missing from Linkerd @git001 ?

**Comment by git001** [comment]
@StrongMonkey thanks.

@wmorgan I assume you mean https://github.com/linkerd/linkerd2. I don't know if I miss something, I just would like to use the well known tool which I use every where therefore I would like to have the choice which LB I can use on the edge. Istio is currently the Hype and customers will ask for it because of that I would like to have a answer.

In general I don't like this "proxy in front of every pod (a.k.a side-car injection)" concept because every hop increases the latency and complexity. This is not specific to linkerd2 it's valid for most service mesh solutions out there. Jm2c.

My prefered solution is to have a ingress controller which talks directly to the endpoints and if a "route" want to have a service mesh "it" can add a annotation to go the long way via "the mesh".

**Comment by munjal-patel** [comment]
We are also trying our Rio. So far looks really good. Great work!

However, we already have quite a few production clusters deployed and meshed using Istio and its Ingress controller.
For that reason, adding yet another Service Mesh into the mix does not make sense.

**Comment by StrongMonkey** [comment]
We are working on the integration. In the future rio will be integrated into rancher and be able to leverage existing istio service mesh that was already deployed into rancher cluster.

**Comment by munjalpatel** [comment]
Thanks for the updates @StrongMonkey . Would happen to know an ETA on Rancher integration? That will help us to decide if we should wait or look for other solutions in a meanwhile.

**Comment by StrongMonkey** [comment]
ETA would be in rancher 2.4. @munjalpatel

**Comment by cbron** [comment]
Closing in favor of: https://github.com/rancher/rio/issues/900

**Comment by munjal-patel** [comment]
> Closing in favor of: #900

@cbron there seems to be a mistake! This issue is #900.

**Comment by cbron** [comment]
Whoops, should be https://github.com/rancher/rio/issues/980

**Comment by rodneytamblyn** [comment]
Re: https://github.com/rancher/rio/issues/900#issuecomment-562776893

> b) We are going to add support for ingress in the next release. Right now all ingress traffic are served by (gloo)[https://github.com/solo-io/gloo], but you will be able to swap it out with your own ingress controller in the next release.

Can someone confirm is this now released - can you choose which ingress you use (for example using Traefic instead of Gloo). Is there documentation?

~ Rodney
