### ISSUE TITLE
Shared env vars in Riofile

### ISSUE THREAD

**Issue by scottrobertson** [rancher/rio#904]
Hey

Is there a way to share env vars across multiple services in a Riofile? Usually i would use config maps for this in k8s directly, but i don't see any documentation on how to use `envFrom` or similar to:

```
envFrom:
  - configMapRef:
      name: syncforynab-config
```

**Comment by StrongMonkey** [comment]
you can try the following example:
```
env:
- FOO=config://syncforynab-config/key
```

There are also some exmaples in https://github.com/rancher/rio/blob/master/docs/workloads.md#examples. We are actually missing docs on riofile example.

**Comment by davidnuzik** [comment]
See the documentation Daishan mentioned. Let us know if you need anything else; closing.
