### ISSUE TITLE
Do not upgrade linkerd by default

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rio#908]
Rio by default run linkerd-install job to upgrade linkerd to match the version that ships along with Rio. We should be able to add a flag to control this behavior and not running upgrade-install-job be default.
This flag will be controlled by feature.options["upgrade"] = "true"

**Comment by StrongMonkey** [comment]
available to test on master.

**Comment by rancher-max** [comment]
Looks like it's working. To test:

1. `rio install`
2. `kubectl get -n riosystemtest job.batch` --> There should be a resource there like `linkerd-install-xadfa`. Keep note of its "AGE" and "NAME".
3. Restart rio controller (kill its pod should be enough)
4. Rerun step (2). Notice that this resource did not change.
5. `rio -s edit configmap/rio-config` --> update `features` to include:
```json
"linkerd": {
  "enabled": true,
  "options": {
    "upgrade": "true"
  }
}
```
6. Run `rio -s cat --key config configmap/rio-config | jq .` to verify changes are present
7. Repeat steps (3) and (4). Now notice that the resource from step (2) does change.

Upgrading linkerd automatically with rio controller is now an "opt-in" feature.
