### ISSUE TITLE
rio pods -c not showing containers 

### ISSUE THREAD

**Issue by rancher-max** [rancher/rio#917]
**Describe the bug**
Help shows that I can use `rio pods -c` to "print containers, not services", but this still just shows the same information as `rio pods` with nothing additional about containers.

**To Reproduce**
1. `rio pods -c`

**Expected behavior**
It should show the containers running in the pod.

**Version**
```
Rio Version: b14c5917-dirty (b14c5917)
Rio CLI Version: dev (HEAD)
```

Checked with both k3s, rke, and gke

**Comment by StrongMonkey** [comment]
I dont think we support this anymore

**Comment by rancher-max** [comment]
Thank you for removing it from the help!
