### ISSUE TITLE
A few issues with rio lite install

### ISSUE THREAD

**Issue by rancher-max** [rancher/rio#922]
Changes to rio install have caused a few issues and annoyances:

**Issues:**
- `rio --system-namespace <value> install` does not map the `-s` flag to the newly chosen system namespace. (https://github.com/rancher/rio/issues/765#issuecomment-564275314)
- Disabling gloo feature does not properly setup ingress (needs http/https port to be set in the clusterdomain)
- Disabling linkerd (which happens by default on cluster with mem < 3gb) causes autoscaling not to work, even though autoscaler is enabled (this likely will be just a documentation thing).

**Annoyances:**
- `rio image` and `rio build-history` give fatal errors instead of something descriptive. (`FATA[0000] buildkitd pod not found` and `FATA[0000] the server could not find the requested resource (get taskruns.tekton.dev)`. Would be better if it said something like `Build feature is not enabled`)
- Editing installation features is a bit of a pain. It is json, but all squished onto one line.

**Comment by rancher-max** [comment]
Running `rio up` or `rio build` both do not turn "Build" feature on.
`rio build` gives error: `FATA[0000] resource name may not be empty`
`rio up` creates a stack but then doesn't do anything with the Build feature so nothing actually happens

**Comment by StrongMonkey** [comment]
Available to test on master now.

**Comment by rancher-max** [comment]
Should `rio uninstall` default to whatever the systemnamespace value is? Right now it defaults to `rio-system` so to uninstall after `rio --system-namespace mytest install` I have to do: `rio uninstall --namespace mytest`

**Comment by rancher-max** [comment]
2 things:
1. `rio image` should enable build feature like `rio build-history` does.

2. Running `rio install --disable-features gloo` after doing a `rio uninstall` does not generate any clusterdomain. Output from the command after it finishes:
```
$ rio install --disable-features gloo
Deploying Rio control plane....
Warning: clusterDomain is not generated
rio controller version dev (HEAD) installed into namespace rio-system
Controller logs are available from `rio systemlogs`

Welcome to Rio!

Run `rio run -p 80:8080 https://github.com/rancher/rio-demo` as an example
```
Nothing useful in systemlogs. Nothing from `kubectl get clusterdomains`, and `rio info` returns an error: `FATA[0000] no system information is generated`

**Comment by rancher-max** [comment]
Looks good in master now!
