### ISSUE TITLE
CoreDNS failing on 0.7.0-rc3

### ISSUE THREAD

**Issue by dantuluri** [rancher/rio#987]
**Describe the bug**
CoreDNS is constantly in status `CrashLoopBackOff` and cannot install Rio properly.

**To Reproduce**
1. Use a x86 Ubuntu 18.04 machine and do `rio install`

**Expected behavior**
Should install CoreDNS properly. Went back and installed 0.7.0rc-2 instead and works.

**Kubernetes version & type (GKE, on-prem)**: `kubectl version`
```
on-prem and 1.0.1 k3s
```
Type:
**Rio version**: `rio info`
```
0.7.0-rc2
```
**Additional context**
`rio system logs`
output:
```
Doesn't work since rio isn't installed.
```

**Comment by vincent99** [comment]
CoreDNS is part of the underlying cluster (in this case k3s), it is not installed by Rio.

**Comment by davidnuzik** [comment]
Please create an issue in rancher/k3s: https://github.com/rancher/k3s/issues/new/choose

It would be helpful to better understand the environment and to get logs from the failing pod in the k3s issue.
