### ISSUE TITLE
Staging service fails with namespace in name rather than as param

### ISSUE THREAD

**Issue by cbron** [rancher/rio#993]
Only occurs in non default namespace

```
rio run -n x:demo nginx
rio stage x:demo v2
 -> x:demo@v2
 -> FATA[0000] failed to find service demo
```

**Comment by rancher-max** [comment]
Working in latest master, commit: c0f480fe. Validated issue scenario and did a regression on default namespace, promoting, arbitrary weights, and a few other basic stage commands with setting image.
